********************************************************************************
**# * ICE
********************************************************************************
// Not using this - was for robustness

// ice
* https://www.stata.com/support/faqs/statistics/mi-versus-ice-and-mim/
* https://www.statalist.org/forums/forum/general-stata-discussion/general/1371095-multiple-imputation
net from http://www.stata-journal.com/software/sj9-3
net install st0067_4.pkg, replace
net from http://www.stata-journal.com/software/sj9-2
net install st0139_1.pkg, replace
net from http://www.homepages.ucl.ac.uk/~ucakjpr/stata
net install mi_ice, replace

use "$created_data\individs_by_duration_wide.dta", clear

egen nmis_age = rmiss(age_focal*)
tab nmis_age, m

drop if nmis_age==17 // for now, just so this is actually complete
drop if birth_yr_all==. // for now, just so this is actually complete
drop if raceth_fixed_focal==. // for now, just so this is actually complete

//  passive(_Ieduc_foca_2:educ_focal0==2 \ _Ieduc_foca_3:educ_focal0==3 \ _Ieduc_foca_4:educ_focal0==4)

#delimit ;

ice weekly_hrs_t_focal* housework_focal* employed_focal* earnings_t_focal* educ_focal* NUM_CHILDREN_* AGE_YOUNG_CHILD_* partnered* TOTAL_INCOME_T_FAMILY* birth_yr_all i.raceth_fixed_focal i.sample_type,
saving(ice_test_bysex, replace) m(10) cycles(10) match(weekly_hrs_t_focal* housework_focal* earnings_t_focal* NUM_CHILDREN_* AGE_YOUNG_CHILD_* TOTAL_INCOME_T_FAMILY*) by(SEX) cmd(educ*:ologit) // dryrun 

/* Employment hours */
eq(weekly_hrs_t_focal0:                 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16 housework_focal0 employed_focal0 earnings_t_focal0 educ_focal0 NUM_CHILDREN_0 AGE_YOUNG_CHILD_0 partnered0 TOTAL_INCOME_T_FAMILY0 i.raceth_fixed_focal birth_yr_all i.sample_type,
weekly_hrs_t_focal1:                weekly_hrs_t_focal0 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16  housework_focal1 employed_focal1 earnings_t_focal1 educ_focal1 NUM_CHILDREN_1 AGE_YOUNG_CHILD_1 partnered1 TOTAL_INCOME_T_FAMILY1 i.raceth_fixed_focal birth_yr_all i.sample_type,
weekly_hrs_t_focal2:               weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16   housework_focal2 employed_focal2 earnings_t_focal2 educ_focal2 NUM_CHILDREN_2 AGE_YOUNG_CHILD_2 partnered2 TOTAL_INCOME_T_FAMILY2 i.raceth_fixed_focal birth_yr_all i.sample_type,
weekly_hrs_t_focal3:              weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16    housework_focal3 employed_focal3 earnings_t_focal3 educ_focal3 NUM_CHILDREN_3 AGE_YOUNG_CHILD_3 partnered3 TOTAL_INCOME_T_FAMILY3 i.raceth_fixed_focal birth_yr_all i.sample_type,
weekly_hrs_t_focal4:             weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16     housework_focal4 employed_focal4 earnings_t_focal4 educ_focal4 NUM_CHILDREN_4 AGE_YOUNG_CHILD_4 partnered4 TOTAL_INCOME_T_FAMILY4 i.raceth_fixed_focal birth_yr_all i.sample_type,
weekly_hrs_t_focal5:            weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16      housework_focal5 employed_focal5 earnings_t_focal5 educ_focal5 NUM_CHILDREN_5 AGE_YOUNG_CHILD_5 partnered5 TOTAL_INCOME_T_FAMILY5 i.raceth_fixed_focal birth_yr_all i.sample_type,
weekly_hrs_t_focal6:           weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16       housework_focal6 employed_focal6 earnings_t_focal6 educ_focal6 NUM_CHILDREN_6 AGE_YOUNG_CHILD_6 partnered6 TOTAL_INCOME_T_FAMILY6 i.raceth_fixed_focal birth_yr_all i.sample_type,
weekly_hrs_t_focal7:          weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16        housework_focal7 employed_focal7 earnings_t_focal7 educ_focal7 NUM_CHILDREN_7 AGE_YOUNG_CHILD_7 partnered7 TOTAL_INCOME_T_FAMILY7 i.raceth_fixed_focal birth_yr_all i.sample_type,
weekly_hrs_t_focal8:         weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16         housework_focal8 employed_focal8 earnings_t_focal8 educ_focal8 NUM_CHILDREN_8 AGE_YOUNG_CHILD_8 partnered8 TOTAL_INCOME_T_FAMILY8 i.raceth_fixed_focal birth_yr_all i.sample_type,
weekly_hrs_t_focal9:        weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16          housework_focal9 employed_focal9 earnings_t_focal9 educ_focal9 NUM_CHILDREN_9 AGE_YOUNG_CHILD_9 partnered9 TOTAL_INCOME_T_FAMILY9 i.raceth_fixed_focal birth_yr_all i.sample_type,
weekly_hrs_t_focal10:       weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16           housework_focal10 employed_focal10 earnings_t_focal10 educ_focal10 NUM_CHILDREN_10 AGE_YOUNG_CHILD_10 partnered10 TOTAL_INCOME_T_FAMILY10 i.raceth_fixed_focal birth_yr_all i.sample_type,
weekly_hrs_t_focal11:      weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16            housework_focal11 employed_focal11 earnings_t_focal11 educ_focal11 NUM_CHILDREN_11 AGE_YOUNG_CHILD_11 partnered11 TOTAL_INCOME_T_FAMILY11 i.raceth_fixed_focal birth_yr_all i.sample_type,
weekly_hrs_t_focal12:     weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16             housework_focal12 employed_focal12 earnings_t_focal12 educ_focal12 NUM_CHILDREN_12 AGE_YOUNG_CHILD_12 partnered12 TOTAL_INCOME_T_FAMILY12 i.raceth_fixed_focal birth_yr_all i.sample_type,
weekly_hrs_t_focal13:    weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t_focal16              housework_focal13 employed_focal13 earnings_t_focal13 educ_focal13 NUM_CHILDREN_13 AGE_YOUNG_CHILD_13 partnered13 TOTAL_INCOME_T_FAMILY13 i.raceth_fixed_focal birth_yr_all i.sample_type,
weekly_hrs_t_focal14:   weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal15 weekly_hrs_t_focal16               housework_focal14 employed_focal14 earnings_t_focal14 educ_focal14 NUM_CHILDREN_14 AGE_YOUNG_CHILD_14 partnered14 TOTAL_INCOME_T_FAMILY14 i.raceth_fixed_focal birth_yr_all i.sample_type,
weekly_hrs_t_focal15:  weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal16                housework_focal15 employed_focal15 earnings_t_focal15 educ_focal15 NUM_CHILDREN_15 AGE_YOUNG_CHILD_15 partnered15 TOTAL_INCOME_T_FAMILY15 i.raceth_fixed_focal birth_yr_all i.sample_type,
weekly_hrs_t_focal16: weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15                 housework_focal16 employed_focal16 earnings_t_focal16 educ_focal16 NUM_CHILDREN_16 AGE_YOUNG_CHILD_16 partnered16 TOTAL_INCOME_T_FAMILY16 i.raceth_fixed_focal birth_yr_all i.sample_type,


/* Housework Hours */
housework_focal0:                 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16 weekly_hrs_t_focal0 employed_focal0 earnings_t_focal0 educ_focal0 i.raceth_fixed_focal birth_yr_all i.sample_type,
housework_focal1:                housework_focal0 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16  weekly_hrs_t_focal1 employed_focal1 earnings_t_focal1 educ_focal1 NUM_CHILDREN_1 AGE_YOUNG_CHILD_1 partnered1 TOTAL_INCOME_T_FAMILY1 i.raceth_fixed_focal birth_yr_all i.sample_type,
housework_focal2:               housework_focal0 housework_focal1 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16   weekly_hrs_t_focal2 employed_focal2 earnings_t_focal2 educ_focal2 NUM_CHILDREN_2 AGE_YOUNG_CHILD_2 partnered2 TOTAL_INCOME_T_FAMILY2 i.raceth_fixed_focal birth_yr_all i.sample_type,
housework_focal3:              housework_focal0 housework_focal1 housework_focal2 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16    weekly_hrs_t_focal3 employed_focal3 earnings_t_focal3 educ_focal3 NUM_CHILDREN_3 AGE_YOUNG_CHILD_3 partnered3 TOTAL_INCOME_T_FAMILY3 i.raceth_fixed_focal birth_yr_all i.sample_type,
housework_focal4:             housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16     weekly_hrs_t_focal4 employed_focal4 earnings_t_focal4 educ_focal4 NUM_CHILDREN_4 AGE_YOUNG_CHILD_4 partnered4 TOTAL_INCOME_T_FAMILY4 i.raceth_fixed_focal birth_yr_all i.sample_type,
housework_focal5:            housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16      weekly_hrs_t_focal5 employed_focal5 earnings_t_focal5 educ_focal5 NUM_CHILDREN_5 AGE_YOUNG_CHILD_5 partnered5 TOTAL_INCOME_T_FAMILY5 i.raceth_fixed_focal birth_yr_all i.sample_type,
housework_focal6:           housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16       weekly_hrs_t_focal6 employed_focal6 earnings_t_focal6 educ_focal6 NUM_CHILDREN_6 AGE_YOUNG_CHILD_6 partnered6 TOTAL_INCOME_T_FAMILY6 i.raceth_fixed_focal birth_yr_all i.sample_type,
housework_focal7:          housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16        weekly_hrs_t_focal7 employed_focal7 earnings_t_focal7 educ_focal7 NUM_CHILDREN_7 AGE_YOUNG_CHILD_7 partnered7 TOTAL_INCOME_T_FAMILY7 i.raceth_fixed_focal birth_yr_all i.sample_type,
housework_focal8:         housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16         weekly_hrs_t_focal8 employed_focal8 earnings_t_focal8 educ_focal8 NUM_CHILDREN_8 AGE_YOUNG_CHILD_8 partnered8 TOTAL_INCOME_T_FAMILY8 i.raceth_fixed_focal birth_yr_all i.sample_type,
housework_focal9:        housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16          weekly_hrs_t_focal9 employed_focal9 earnings_t_focal9 educ_focal9 NUM_CHILDREN_9 AGE_YOUNG_CHILD_9 partnered9 TOTAL_INCOME_T_FAMILY9 i.raceth_fixed_focal birth_yr_all i.sample_type,
housework_focal10:       housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16           weekly_hrs_t_focal10 employed_focal10 earnings_t_focal10 educ_focal10 NUM_CHILDREN_10 AGE_YOUNG_CHILD_10 partnered10 TOTAL_INCOME_T_FAMILY10 i.raceth_fixed_focal birth_yr_all i.sample_type,
housework_focal11:      housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal12 housework_focal13 housework_focal14 housework_focal15 housework_focal16            weekly_hrs_t_focal11 employed_focal11 earnings_t_focal11 educ_focal11 NUM_CHILDREN_11 AGE_YOUNG_CHILD_11 partnered11 TOTAL_INCOME_T_FAMILY11 i.raceth_fixed_focal birth_yr_all i.sample_type,
housework_focal12:     housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal13 housework_focal14 housework_focal15 housework_focal16             weekly_hrs_t_focal12 employed_focal12 earnings_t_focal12 educ_focal12 NUM_CHILDREN_12 AGE_YOUNG_CHILD_12 partnered12 TOTAL_INCOME_T_FAMILY12 i.raceth_fixed_focal birth_yr_all i.sample_type,
housework_focal13:    housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal14 housework_focal15 housework_focal16              weekly_hrs_t_focal13 employed_focal13 earnings_t_focal13 educ_focal13 NUM_CHILDREN_13 AGE_YOUNG_CHILD_13 partnered13 TOTAL_INCOME_T_FAMILY13 i.raceth_fixed_focal birth_yr_all i.sample_type,
housework_focal14:   housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal15 housework_focal16               weekly_hrs_t_focal14 employed_focal14 earnings_t_focal14 educ_focal14 NUM_CHILDREN_14 AGE_YOUNG_CHILD_14 partnered14 TOTAL_INCOME_T_FAMILY14 i.raceth_fixed_focal birth_yr_all i.sample_type,
housework_focal15:  housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal16                weekly_hrs_t_focal15 employed_focal15 earnings_t_focal15 educ_focal15 NUM_CHILDREN_15 AGE_YOUNG_CHILD_15 partnered15 TOTAL_INCOME_T_FAMILY15 i.raceth_fixed_focal birth_yr_all i.sample_type,
housework_focal16: housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15                 weekly_hrs_t_focal16 employed_focal16 earnings_t_focal16 educ_focal16 NUM_CHILDREN_16 AGE_YOUNG_CHILD_16 partnered16 TOTAL_INCOME_T_FAMILY16 i.raceth_fixed_focal birth_yr_all i.sample_type,


/* Employment Status*/
employed_focal0:                 employed_focal1 employed_focal2 employed_focal3 employed_focal4 employed_focal5 employed_focal6 employed_focal7 employed_focal8 employed_focal9 employed_focal10 employed_focal11 employed_focal12 employed_focal13 employed_focal14 employed_focal15 employed_focal16  housework_focal0  educ_focal0 NUM_CHILDREN_0 AGE_YOUNG_CHILD_0 partnered0 TOTAL_INCOME_T_FAMILY0 i.raceth_fixed_focal birth_yr_all i.sample_type,
employed_focal1:                employed_focal0 employed_focal2 employed_focal3 employed_focal4 employed_focal5 employed_focal6 employed_focal7 employed_focal8 employed_focal9 employed_focal10 employed_focal11 employed_focal12 employed_focal13 employed_focal14 employed_focal15 employed_focal16  weekly_hrs_t_focal0 housework_focal1 earnings_t_focal0 educ_focal1 NUM_CHILDREN_1 AGE_YOUNG_CHILD_1 partnered1 TOTAL_INCOME_T_FAMILY1 i.raceth_fixed_focal birth_yr_all i.sample_type,
employed_focal2:               employed_focal0 employed_focal1 employed_focal3 employed_focal4 employed_focal5 employed_focal6 employed_focal7 employed_focal8 employed_focal9 employed_focal10 employed_focal11 employed_focal12 employed_focal13 employed_focal14 employed_focal15 employed_focal16   weekly_hrs_t_focal1 housework_focal2 earnings_t_focal1 educ_focal2 NUM_CHILDREN_2 AGE_YOUNG_CHILD_2 partnered2 TOTAL_INCOME_T_FAMILY2 i.raceth_fixed_focal birth_yr_all i.sample_type,
employed_focal3:              employed_focal0 employed_focal1 employed_focal2 employed_focal4 employed_focal5 employed_focal6 employed_focal7 employed_focal8 employed_focal9 employed_focal10 employed_focal11 employed_focal12 employed_focal13 employed_focal14 employed_focal15 employed_focal16    weekly_hrs_t_focal2 housework_focal3 earnings_t_focal2 educ_focal3 NUM_CHILDREN_3 AGE_YOUNG_CHILD_3 partnered3 TOTAL_INCOME_T_FAMILY3 i.raceth_fixed_focal birth_yr_all i.sample_type,
employed_focal4:             employed_focal0 employed_focal1 employed_focal2 employed_focal3 employed_focal5 employed_focal6 employed_focal7 employed_focal8 employed_focal9 employed_focal10 employed_focal11 employed_focal12 employed_focal13 employed_focal14 employed_focal15 employed_focal16     weekly_hrs_t_focal3 housework_focal4 earnings_t_focal3 educ_focal4 NUM_CHILDREN_4 AGE_YOUNG_CHILD_4 partnered4 TOTAL_INCOME_T_FAMILY4 i.raceth_fixed_focal birth_yr_all i.sample_type,
employed_focal5:            employed_focal0 employed_focal1 employed_focal2 employed_focal3 employed_focal4 employed_focal6 employed_focal7 employed_focal8 employed_focal9 employed_focal10 employed_focal11 employed_focal12 employed_focal13 employed_focal14 employed_focal15 employed_focal16      weekly_hrs_t_focal4 housework_focal5 earnings_t_focal4 educ_focal5 NUM_CHILDREN_5 AGE_YOUNG_CHILD_5 partnered5 TOTAL_INCOME_T_FAMILY5 i.raceth_fixed_focal birth_yr_all i.sample_type,
employed_focal6:           employed_focal0 employed_focal1 employed_focal2 employed_focal3 employed_focal4 employed_focal5 employed_focal7 employed_focal8 employed_focal9 employed_focal10 employed_focal11 employed_focal12 employed_focal13 employed_focal14 employed_focal15 employed_focal16       weekly_hrs_t_focal5 housework_focal6 earnings_t_focal5 educ_focal6 NUM_CHILDREN_6 AGE_YOUNG_CHILD_6 partnered6 TOTAL_INCOME_T_FAMILY6 i.raceth_fixed_focal birth_yr_all i.sample_type,
employed_focal7:          employed_focal0 employed_focal1 employed_focal2 employed_focal3 employed_focal4 employed_focal5 employed_focal6 employed_focal8 employed_focal9 employed_focal10 employed_focal11 employed_focal12 employed_focal13 employed_focal14 employed_focal15 employed_focal16        weekly_hrs_t_focal6 housework_focal7 earnings_t_focal6 educ_focal7 NUM_CHILDREN_7 AGE_YOUNG_CHILD_7 partnered7 TOTAL_INCOME_T_FAMILY7 i.raceth_fixed_focal birth_yr_all i.sample_type,
employed_focal8:         employed_focal0 employed_focal1 employed_focal2 employed_focal3 employed_focal4 employed_focal5 employed_focal6 employed_focal7 employed_focal9 employed_focal10 employed_focal11 employed_focal12 employed_focal13 employed_focal14 employed_focal15 employed_focal16         weekly_hrs_t_focal7 housework_focal8 earnings_t_focal7 educ_focal8 NUM_CHILDREN_8 AGE_YOUNG_CHILD_8 partnered8 TOTAL_INCOME_T_FAMILY8 i.raceth_fixed_focal birth_yr_all i.sample_type,
employed_focal9:        employed_focal0 employed_focal1 employed_focal2 employed_focal3 employed_focal4 employed_focal5 employed_focal6 employed_focal7 employed_focal8 employed_focal10 employed_focal11 employed_focal12 employed_focal13 employed_focal14 employed_focal15 employed_focal16          weekly_hrs_t_focal8 housework_focal9 earnings_t_focal8 educ_focal9 NUM_CHILDREN_9 AGE_YOUNG_CHILD_9 partnered9 TOTAL_INCOME_T_FAMILY9 i.raceth_fixed_focal birth_yr_all i.sample_type,
employed_focal10:       employed_focal0 employed_focal1 employed_focal2 employed_focal3 employed_focal4 employed_focal5 employed_focal6 employed_focal7 employed_focal8 employed_focal9 employed_focal11 employed_focal12 employed_focal13 employed_focal14 employed_focal15 employed_focal16           weekly_hrs_t_focal9 housework_focal10 earnings_t_focal9 educ_focal10 NUM_CHILDREN_10 AGE_YOUNG_CHILD_10 partnered10 TOTAL_INCOME_T_FAMILY10 i.raceth_fixed_focal birth_yr_all i.sample_type,
employed_focal11:      employed_focal0 employed_focal1 employed_focal2 employed_focal3 employed_focal4 employed_focal5 employed_focal6 employed_focal7 employed_focal8 employed_focal9 employed_focal10 employed_focal12 employed_focal13 employed_focal14 employed_focal15 employed_focal16            weekly_hrs_t_focal10 housework_focal11 earnings_t_focal10 educ_focal11 NUM_CHILDREN_11 AGE_YOUNG_CHILD_11 partnered11 TOTAL_INCOME_T_FAMILY11 i.raceth_fixed_focal birth_yr_all i.sample_type,
employed_focal12:     employed_focal0 employed_focal1 employed_focal2 employed_focal3 employed_focal4 employed_focal5 employed_focal6 employed_focal7 employed_focal8 employed_focal9 employed_focal10 employed_focal11 employed_focal13 employed_focal14 employed_focal15 employed_focal16             weekly_hrs_t_focal11 housework_focal12 earnings_t_focal11 educ_focal12 NUM_CHILDREN_12 AGE_YOUNG_CHILD_12 partnered12 TOTAL_INCOME_T_FAMILY12 i.raceth_fixed_focal birth_yr_all i.sample_type,
employed_focal13:    employed_focal0 employed_focal1 employed_focal2 employed_focal3 employed_focal4 employed_focal5 employed_focal6 employed_focal7 employed_focal8 employed_focal9 employed_focal10 employed_focal11 employed_focal12 employed_focal14 employed_focal15 employed_focal16              weekly_hrs_t_focal12 housework_focal13 earnings_t_focal12 educ_focal13 NUM_CHILDREN_13 AGE_YOUNG_CHILD_13 partnered13 TOTAL_INCOME_T_FAMILY13 i.raceth_fixed_focal birth_yr_all i.sample_type,
employed_focal14:   employed_focal0 employed_focal1 employed_focal2 employed_focal3 employed_focal4 employed_focal5 employed_focal6 employed_focal7 employed_focal8 employed_focal9 employed_focal10 employed_focal11 employed_focal12 employed_focal13 employed_focal15 employed_focal16               weekly_hrs_t_focal13 housework_focal14 earnings_t_focal13 educ_focal14 NUM_CHILDREN_14 AGE_YOUNG_CHILD_14 partnered14 TOTAL_INCOME_T_FAMILY14 i.raceth_fixed_focal birth_yr_all i.sample_type,
employed_focal15:  employed_focal0 employed_focal1 employed_focal2 employed_focal3 employed_focal4 employed_focal5 employed_focal6 employed_focal7 employed_focal8 employed_focal9 employed_focal10 employed_focal11 employed_focal12 employed_focal13 employed_focal14 employed_focal16                weekly_hrs_t_focal14 housework_focal15 earnings_t_focal14 educ_focal15 NUM_CHILDREN_15 AGE_YOUNG_CHILD_15 partnered15 TOTAL_INCOME_T_FAMILY15 i.raceth_fixed_focal birth_yr_all i.sample_type,
employed_focal16: employed_focal0 employed_focal1 employed_focal2 employed_focal3 employed_focal4 employed_focal5 employed_focal6 employed_focal7 employed_focal8 employed_focal9 employed_focal10 employed_focal11 employed_focal12 employed_focal13 employed_focal14 employed_focal15                 weekly_hrs_t_focal15 housework_focal16 earnings_t_focal15 educ_focal16 NUM_CHILDREN_16 AGE_YOUNG_CHILD_16 partnered16 TOTAL_INCOME_T_FAMILY16 i.raceth_fixed_focal birth_yr_all i.sample_type,

/* Earnings */
earnings_t_focal0:                 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16 weekly_hrs_t_focal0 employed_focal0 housework_focal0 educ_focal0 NUM_CHILDREN_0 AGE_YOUNG_CHILD_0 partnered0 TOTAL_INCOME_T_FAMILY0 i.raceth_fixed_focal birth_yr_all i.sample_type,
earnings_t_focal1:                earnings_t_focal0 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16  weekly_hrs_t_focal1 employed_focal1 housework_focal1 educ_focal1 NUM_CHILDREN_1 AGE_YOUNG_CHILD_1 partnered1 TOTAL_INCOME_T_FAMILY1 i.raceth_fixed_focal birth_yr_all i.sample_type,
earnings_t_focal2:               earnings_t_focal0 earnings_t_focal1 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16   weekly_hrs_t_focal2 employed_focal2 housework_focal2 educ_focal2 NUM_CHILDREN_2 AGE_YOUNG_CHILD_2 partnered2 TOTAL_INCOME_T_FAMILY2 i.raceth_fixed_focal birth_yr_all i.sample_type,
earnings_t_focal3:              earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16    weekly_hrs_t_focal3 employed_focal3 housework_focal3 educ_focal3 NUM_CHILDREN_3 AGE_YOUNG_CHILD_3 partnered3 TOTAL_INCOME_T_FAMILY3 i.raceth_fixed_focal birth_yr_all i.sample_type,
earnings_t_focal4:             earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16     weekly_hrs_t_focal4 employed_focal4 housework_focal4 educ_focal4 NUM_CHILDREN_4 AGE_YOUNG_CHILD_4 partnered4 TOTAL_INCOME_T_FAMILY4 i.raceth_fixed_focal birth_yr_all i.sample_type,
earnings_t_focal5:            earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16      weekly_hrs_t_focal5 employed_focal5 housework_focal5 educ_focal5 NUM_CHILDREN_5 AGE_YOUNG_CHILD_5 partnered5 TOTAL_INCOME_T_FAMILY5 i.raceth_fixed_focal birth_yr_all i.sample_type,
earnings_t_focal6:           earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16       weekly_hrs_t_focal6 employed_focal6 housework_focal6 educ_focal6 NUM_CHILDREN_6 AGE_YOUNG_CHILD_6 partnered6 TOTAL_INCOME_T_FAMILY6 i.raceth_fixed_focal birth_yr_all i.sample_type,
earnings_t_focal7:          earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16        weekly_hrs_t_focal7 employed_focal7 housework_focal7 educ_focal7 NUM_CHILDREN_7 AGE_YOUNG_CHILD_7 partnered7 TOTAL_INCOME_T_FAMILY7 i.raceth_fixed_focal birth_yr_all i.sample_type,
earnings_t_focal8:         earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16         weekly_hrs_t_focal8 employed_focal8 housework_focal8 educ_focal8 NUM_CHILDREN_8 AGE_YOUNG_CHILD_8 partnered8 TOTAL_INCOME_T_FAMILY8 i.raceth_fixed_focal birth_yr_all i.sample_type,
earnings_t_focal9:        earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16          weekly_hrs_t_focal9 employed_focal9 housework_focal9 educ_focal9 NUM_CHILDREN_9 AGE_YOUNG_CHILD_9 partnered9 TOTAL_INCOME_T_FAMILY9 i.raceth_fixed_focal birth_yr_all i.sample_type,
earnings_t_focal10:       earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16           weekly_hrs_t_focal10 employed_focal10 housework_focal10 educ_focal10 NUM_CHILDREN_10 AGE_YOUNG_CHILD_10 partnered10 TOTAL_INCOME_T_FAMILY10 i.raceth_fixed_focal birth_yr_all i.sample_type,
earnings_t_focal11:      earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16            weekly_hrs_t_focal11 employed_focal11 housework_focal11 educ_focal11 NUM_CHILDREN_11 AGE_YOUNG_CHILD_11 partnered11 TOTAL_INCOME_T_FAMILY11 i.raceth_fixed_focal birth_yr_all i.sample_type,
earnings_t_focal12:     earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16             weekly_hrs_t_focal12 employed_focal12 housework_focal12 educ_focal12 NUM_CHILDREN_12 AGE_YOUNG_CHILD_12 partnered12 TOTAL_INCOME_T_FAMILY12 i.raceth_fixed_focal birth_yr_all i.sample_type,
earnings_t_focal13:    earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal14 earnings_t_focal15 earnings_t_focal16              weekly_hrs_t_focal13 employed_focal13 housework_focal13 educ_focal13 NUM_CHILDREN_13 AGE_YOUNG_CHILD_13 partnered13 TOTAL_INCOME_T_FAMILY13 i.raceth_fixed_focal birth_yr_all i.sample_type,
earnings_t_focal14:   earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal15 earnings_t_focal16               weekly_hrs_t_focal14 employed_focal14 housework_focal14 educ_focal14 NUM_CHILDREN_14 AGE_YOUNG_CHILD_14 partnered14 TOTAL_INCOME_T_FAMILY14 i.raceth_fixed_focal birth_yr_all i.sample_type,
earnings_t_focal15:  earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal16                weekly_hrs_t_focal15 employed_focal15 housework_focal15 educ_focal15 NUM_CHILDREN_15 AGE_YOUNG_CHILD_15 partnered15 TOTAL_INCOME_T_FAMILY15 i.raceth_fixed_focal birth_yr_all i.sample_type,
earnings_t_focal16: earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15                 weekly_hrs_t_focal16 employed_focal16 housework_focal16 educ_focal16 NUM_CHILDREN_16 AGE_YOUNG_CHILD_16 partnered16 TOTAL_INCOME_T_FAMILY16 i.raceth_fixed_focal birth_yr_all i.sample_type,

/* Education */
educ_focal0:                 educ_focal1 educ_focal2 educ_focal3 educ_focal4 educ_focal5 educ_focal6 educ_focal7 educ_focal8 educ_focal9 educ_focal10 educ_focal11 educ_focal12 educ_focal13 educ_focal14 educ_focal15 educ_focal16 weekly_hrs_t_focal0 employed_focal0 housework_focal0 earnings_t_focal0 NUM_CHILDREN_0 AGE_YOUNG_CHILD_0 partnered0 TOTAL_INCOME_T_FAMILY0 i.raceth_fixed_focal birth_yr_all i.sample_type,
educ_focal1:                educ_focal0 educ_focal2 educ_focal3 educ_focal4 educ_focal5 educ_focal6 educ_focal7 educ_focal8 educ_focal9 educ_focal10 educ_focal11 educ_focal12 educ_focal13 educ_focal14 educ_focal15 educ_focal16  weekly_hrs_t_focal1 employed_focal1 housework_focal1 earnings_t_focal1 NUM_CHILDREN_1 AGE_YOUNG_CHILD_1 partnered1 TOTAL_INCOME_T_FAMILY1 i.raceth_fixed_focal birth_yr_all i.sample_type,
educ_focal2:               educ_focal0 educ_focal1 educ_focal3 educ_focal4 educ_focal5 educ_focal6 educ_focal7 educ_focal8 educ_focal9 educ_focal10 educ_focal11 educ_focal12 educ_focal13 educ_focal14 educ_focal15 educ_focal16   weekly_hrs_t_focal2 employed_focal2 housework_focal2 earnings_t_focal2 NUM_CHILDREN_2 AGE_YOUNG_CHILD_2 partnered2 TOTAL_INCOME_T_FAMILY2 i.raceth_fixed_focal birth_yr_all i.sample_type,
educ_focal3:              educ_focal0 educ_focal1 educ_focal2 educ_focal4 educ_focal5 educ_focal6 educ_focal7 educ_focal8 educ_focal9 educ_focal10 educ_focal11 educ_focal12 educ_focal13 educ_focal14 educ_focal15 educ_focal16    weekly_hrs_t_focal3 employed_focal3 housework_focal3 earnings_t_focal3 NUM_CHILDREN_3 AGE_YOUNG_CHILD_3 partnered3 TOTAL_INCOME_T_FAMILY3 i.raceth_fixed_focal birth_yr_all i.sample_type,
educ_focal4:             educ_focal0 educ_focal1 educ_focal2 educ_focal3 educ_focal5 educ_focal6 educ_focal7 educ_focal8 educ_focal9 educ_focal10 educ_focal11 educ_focal12 educ_focal13 educ_focal14 educ_focal15 educ_focal16     weekly_hrs_t_focal4 employed_focal4 housework_focal4 earnings_t_focal4 NUM_CHILDREN_4 AGE_YOUNG_CHILD_4 partnered4 TOTAL_INCOME_T_FAMILY4 i.raceth_fixed_focal birth_yr_all i.sample_type,
educ_focal5:            educ_focal0 educ_focal1 educ_focal2 educ_focal3 educ_focal4 educ_focal6 educ_focal7 educ_focal8 educ_focal9 educ_focal10 educ_focal11 educ_focal12 educ_focal13 educ_focal14 educ_focal15 educ_focal16      weekly_hrs_t_focal5 employed_focal5 housework_focal5 earnings_t_focal5 NUM_CHILDREN_5 AGE_YOUNG_CHILD_5 partnered5 TOTAL_INCOME_T_FAMILY5 i.raceth_fixed_focal birth_yr_all i.sample_type,
educ_focal6:           educ_focal0 educ_focal1 educ_focal2 educ_focal3 educ_focal4 educ_focal5 educ_focal7 educ_focal8 educ_focal9 educ_focal10 educ_focal11 educ_focal12 educ_focal13 educ_focal14 educ_focal15 educ_focal16       weekly_hrs_t_focal6 employed_focal6 housework_focal6 earnings_t_focal6 NUM_CHILDREN_6 AGE_YOUNG_CHILD_6 partnered6 TOTAL_INCOME_T_FAMILY6 i.raceth_fixed_focal birth_yr_all i.sample_type,
educ_focal7:          educ_focal0 educ_focal1 educ_focal2 educ_focal3 educ_focal4 educ_focal5 educ_focal6 educ_focal8 educ_focal9 educ_focal10 educ_focal11 educ_focal12 educ_focal13 educ_focal14 educ_focal15 educ_focal16        weekly_hrs_t_focal7 employed_focal7 housework_focal7 earnings_t_focal7 NUM_CHILDREN_7 AGE_YOUNG_CHILD_7 partnered7 TOTAL_INCOME_T_FAMILY7 i.raceth_fixed_focal birth_yr_all i.sample_type,
educ_focal8:         educ_focal0 educ_focal1 educ_focal2 educ_focal3 educ_focal4 educ_focal5 educ_focal6 educ_focal7 educ_focal9 educ_focal10 educ_focal11 educ_focal12 educ_focal13 educ_focal14 educ_focal15 educ_focal16         weekly_hrs_t_focal8 employed_focal8 housework_focal8 earnings_t_focal8 NUM_CHILDREN_8 AGE_YOUNG_CHILD_8 partnered8 TOTAL_INCOME_T_FAMILY8 i.raceth_fixed_focal birth_yr_all i.sample_type,
educ_focal9:        educ_focal0 educ_focal1 educ_focal2 educ_focal3 educ_focal4 educ_focal5 educ_focal6 educ_focal7 educ_focal8 educ_focal10 educ_focal11 educ_focal12 educ_focal13 educ_focal14 educ_focal15 educ_focal16          weekly_hrs_t_focal9 employed_focal9 housework_focal9 earnings_t_focal9 NUM_CHILDREN_9 AGE_YOUNG_CHILD_9 partnered9 TOTAL_INCOME_T_FAMILY9 i.raceth_fixed_focal birth_yr_all i.sample_type,
educ_focal10:       educ_focal0 educ_focal1 educ_focal2 educ_focal3 educ_focal4 educ_focal5 educ_focal6 educ_focal7 educ_focal8 educ_focal9 educ_focal11 educ_focal12 educ_focal13 educ_focal14 educ_focal15 educ_focal16           weekly_hrs_t_focal10 employed_focal10 housework_focal10 earnings_t_focal10 NUM_CHILDREN_10 AGE_YOUNG_CHILD_10 partnered10 TOTAL_INCOME_T_FAMILY10 i.raceth_fixed_focal birth_yr_all i.sample_type,
educ_focal11:      educ_focal0 educ_focal1 educ_focal2 educ_focal3 educ_focal4 educ_focal5 educ_focal6 educ_focal7 educ_focal8 educ_focal9 educ_focal10 educ_focal12 educ_focal13 educ_focal14 educ_focal15 educ_focal16            weekly_hrs_t_focal11 employed_focal11 housework_focal11 earnings_t_focal11 NUM_CHILDREN_11 AGE_YOUNG_CHILD_11 partnered11 TOTAL_INCOME_T_FAMILY11 i.raceth_fixed_focal birth_yr_all i.sample_type,
educ_focal12:     educ_focal0 educ_focal1 educ_focal2 educ_focal3 educ_focal4 educ_focal5 educ_focal6 educ_focal7 educ_focal8 educ_focal9 educ_focal10 educ_focal11 educ_focal13 educ_focal14 educ_focal15 educ_focal16             weekly_hrs_t_focal12 employed_focal12 housework_focal12 earnings_t_focal12 NUM_CHILDREN_12 AGE_YOUNG_CHILD_12 partnered12 TOTAL_INCOME_T_FAMILY12 i.raceth_fixed_focal birth_yr_all i.sample_type,
educ_focal13:    educ_focal0 educ_focal1 educ_focal2 educ_focal3 educ_focal4 educ_focal5 educ_focal6 educ_focal7 educ_focal8 educ_focal9 educ_focal10 educ_focal11 educ_focal12 educ_focal14 educ_focal15 educ_focal16              weekly_hrs_t_focal13 employed_focal13 housework_focal13 earnings_t_focal13 NUM_CHILDREN_13 AGE_YOUNG_CHILD_13 partnered13 TOTAL_INCOME_T_FAMILY13 i.raceth_fixed_focal birth_yr_all i.sample_type,
educ_focal14:   educ_focal0 educ_focal1 educ_focal2 educ_focal3 educ_focal4 educ_focal5 educ_focal6 educ_focal7 educ_focal8 educ_focal9 educ_focal10 educ_focal11 educ_focal12 educ_focal13 educ_focal15 educ_focal16               weekly_hrs_t_focal14 employed_focal14 housework_focal14 earnings_t_focal14 NUM_CHILDREN_14 AGE_YOUNG_CHILD_14 partnered14 TOTAL_INCOME_T_FAMILY14 i.raceth_fixed_focal birth_yr_all i.sample_type,
educ_focal15:  educ_focal0 educ_focal1 educ_focal2 educ_focal3 educ_focal4 educ_focal5 educ_focal6 educ_focal7 educ_focal8 educ_focal9 educ_focal10 educ_focal11 educ_focal12 educ_focal13 educ_focal14 educ_focal16                weekly_hrs_t_focal15 employed_focal15 housework_focal15 earnings_t_focal15 NUM_CHILDREN_15 AGE_YOUNG_CHILD_15 partnered15 TOTAL_INCOME_T_FAMILY15 i.raceth_fixed_focal birth_yr_all i.sample_type,
educ_focal16: educ_focal0 educ_focal1 educ_focal2 educ_focal3 educ_focal4 educ_focal5 educ_focal6 educ_focal7 educ_focal8 educ_focal9 educ_focal10 educ_focal11 educ_focal12 educ_focal13 educ_focal14 educ_focal15                 weekly_hrs_t_focal16 employed_focal16 housework_focal16 earnings_t_focal16 NUM_CHILDREN_16 AGE_YOUNG_CHILD_16 partnered16 TOTAL_INCOME_T_FAMILY16 i.raceth_fixed_focal birth_yr_all i.sample_type,

/* Number of Children */
NUM_CHILDREN_0:                 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16 weekly_hrs_t_focal0 employed_focal0 housework_focal0 educ_focal0 earnings_t_focal0 AGE_YOUNG_CHILD_0 partnered0 TOTAL_INCOME_T_FAMILY0 i.raceth_fixed_focal birth_yr_all i.sample_type,
NUM_CHILDREN_1:                NUM_CHILDREN_0 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16  weekly_hrs_t_focal1 employed_focal1 housework_focal1 educ_focal1 earnings_t_focal1 AGE_YOUNG_CHILD_1 partnered1 TOTAL_INCOME_T_FAMILY1 i.raceth_fixed_focal birth_yr_all i.sample_type,
NUM_CHILDREN_2:               NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16   weekly_hrs_t_focal2 employed_focal2 housework_focal2 educ_focal2 earnings_t_focal2 AGE_YOUNG_CHILD_2 partnered2 TOTAL_INCOME_T_FAMILY2 i.raceth_fixed_focal birth_yr_all i.sample_type,
NUM_CHILDREN_3:              NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16    weekly_hrs_t_focal3 employed_focal3 housework_focal3 educ_focal3 earnings_t_focal3 AGE_YOUNG_CHILD_3 partnered3 TOTAL_INCOME_T_FAMILY3 i.raceth_fixed_focal birth_yr_all i.sample_type,
NUM_CHILDREN_4:             NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16     weekly_hrs_t_focal4 employed_focal4 housework_focal4 educ_focal4 earnings_t_focal4 AGE_YOUNG_CHILD_4 partnered4 TOTAL_INCOME_T_FAMILY4 i.raceth_fixed_focal birth_yr_all i.sample_type,
NUM_CHILDREN_5:            NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16      weekly_hrs_t_focal5 employed_focal5 housework_focal5 educ_focal5 earnings_t_focal5 AGE_YOUNG_CHILD_5 partnered5 TOTAL_INCOME_T_FAMILY5 i.raceth_fixed_focal birth_yr_all i.sample_type,
NUM_CHILDREN_6:           NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16       weekly_hrs_t_focal6 employed_focal6 housework_focal6 educ_focal6 earnings_t_focal6 AGE_YOUNG_CHILD_6 partnered6 TOTAL_INCOME_T_FAMILY6 i.raceth_fixed_focal birth_yr_all i.sample_type,
NUM_CHILDREN_7:          NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16        weekly_hrs_t_focal7 employed_focal7 housework_focal7 educ_focal7 earnings_t_focal7 AGE_YOUNG_CHILD_7 partnered7 TOTAL_INCOME_T_FAMILY7 i.raceth_fixed_focal birth_yr_all i.sample_type,
NUM_CHILDREN_8:         NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16         weekly_hrs_t_focal8 employed_focal8 housework_focal8 educ_focal8 earnings_t_focal8 AGE_YOUNG_CHILD_8 partnered8 TOTAL_INCOME_T_FAMILY8 i.raceth_fixed_focal birth_yr_all i.sample_type,
NUM_CHILDREN_9:        NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16          weekly_hrs_t_focal9 employed_focal9 housework_focal9 educ_focal9 earnings_t_focal9 AGE_YOUNG_CHILD_9 partnered9 TOTAL_INCOME_T_FAMILY9 i.raceth_fixed_focal birth_yr_all i.sample_type,
NUM_CHILDREN_10:       NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16           weekly_hrs_t_focal10 employed_focal10 housework_focal10 educ_focal10 earnings_t_focal10 AGE_YOUNG_CHILD_10 partnered10 TOTAL_INCOME_T_FAMILY10 i.raceth_fixed_focal birth_yr_all i.sample_type,
NUM_CHILDREN_11:      NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16            weekly_hrs_t_focal11 employed_focal11 housework_focal11 educ_focal11 earnings_t_focal11 AGE_YOUNG_CHILD_11 partnered11 TOTAL_INCOME_T_FAMILY11 i.raceth_fixed_focal birth_yr_all i.sample_type,
NUM_CHILDREN_12:     NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16             weekly_hrs_t_focal12 employed_focal12 housework_focal12 educ_focal12 earnings_t_focal12 AGE_YOUNG_CHILD_12 partnered12 TOTAL_INCOME_T_FAMILY12 i.raceth_fixed_focal birth_yr_all i.sample_type,
NUM_CHILDREN_13:    NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_14 NUM_CHILDREN_15 NUM_CHILDREN_16              weekly_hrs_t_focal13 employed_focal13 housework_focal13 educ_focal13 earnings_t_focal13 AGE_YOUNG_CHILD_13 partnered13 TOTAL_INCOME_T_FAMILY13 i.raceth_fixed_focal birth_yr_all i.sample_type,
NUM_CHILDREN_14:   NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_15 NUM_CHILDREN_16               weekly_hrs_t_focal14 employed_focal14 housework_focal14 educ_focal14 earnings_t_focal14 AGE_YOUNG_CHILD_14 partnered14 TOTAL_INCOME_T_FAMILY14 i.raceth_fixed_focal birth_yr_all i.sample_type,
NUM_CHILDREN_15:  NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_16                weekly_hrs_t_focal15 employed_focal15 housework_focal15 educ_focal15 earnings_t_focal15 AGE_YOUNG_CHILD_15 partnered15 TOTAL_INCOME_T_FAMILY15 i.raceth_fixed_focal birth_yr_all i.sample_type,
NUM_CHILDREN_16: NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15                 weekly_hrs_t_focal16 employed_focal16 housework_focal16 educ_focal16 earnings_t_focal16 AGE_YOUNG_CHILD_16 partnered16 TOTAL_INCOME_T_FAMILY16 i.raceth_fixed_focal birth_yr_all i.sample_type,

/* Age of Youngest Child */
AGE_YOUNG_CHILD_0:                 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16 weekly_hrs_t_focal0 employed_focal0 housework_focal0 educ_focal0 earnings_t_focal0 NUM_CHILDREN_0 partnered0 TOTAL_INCOME_T_FAMILY0 i.raceth_fixed_focal birth_yr_all i.sample_type,
AGE_YOUNG_CHILD_1:                AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16  weekly_hrs_t_focal1 employed_focal1 housework_focal1 educ_focal1 earnings_t_focal1 NUM_CHILDREN_1 partnered1 TOTAL_INCOME_T_FAMILY1 i.raceth_fixed_focal birth_yr_all i.sample_type,
AGE_YOUNG_CHILD_2:               AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16   weekly_hrs_t_focal2 employed_focal2 housework_focal2 educ_focal2 earnings_t_focal2 NUM_CHILDREN_2 partnered2 TOTAL_INCOME_T_FAMILY2 i.raceth_fixed_focal birth_yr_all i.sample_type,
AGE_YOUNG_CHILD_3:              AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16    weekly_hrs_t_focal3 employed_focal3 housework_focal3 educ_focal3 earnings_t_focal3 NUM_CHILDREN_3 partnered3 TOTAL_INCOME_T_FAMILY3 i.raceth_fixed_focal birth_yr_all i.sample_type,
AGE_YOUNG_CHILD_4:             AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16     weekly_hrs_t_focal4 employed_focal4 housework_focal4 educ_focal4 earnings_t_focal4 NUM_CHILDREN_4 partnered4 TOTAL_INCOME_T_FAMILY4 i.raceth_fixed_focal birth_yr_all i.sample_type,
AGE_YOUNG_CHILD_5:            AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16      weekly_hrs_t_focal5 employed_focal5 housework_focal5 educ_focal5 earnings_t_focal5 NUM_CHILDREN_5 partnered5 TOTAL_INCOME_T_FAMILY5 i.raceth_fixed_focal birth_yr_all i.sample_type,
AGE_YOUNG_CHILD_6:           AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16       weekly_hrs_t_focal6 employed_focal6 housework_focal6 educ_focal6 earnings_t_focal6 NUM_CHILDREN_6 partnered6 TOTAL_INCOME_T_FAMILY6 i.raceth_fixed_focal birth_yr_all i.sample_type,
AGE_YOUNG_CHILD_7:          AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16        weekly_hrs_t_focal7 employed_focal7 housework_focal7 educ_focal7 earnings_t_focal7 NUM_CHILDREN_7 partnered7 TOTAL_INCOME_T_FAMILY7 i.raceth_fixed_focal birth_yr_all i.sample_type,
AGE_YOUNG_CHILD_8:         AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16         weekly_hrs_t_focal8 employed_focal8 housework_focal8 educ_focal8 earnings_t_focal8 NUM_CHILDREN_8 partnered8 TOTAL_INCOME_T_FAMILY8 i.raceth_fixed_focal birth_yr_all i.sample_type,
AGE_YOUNG_CHILD_9:        AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16          weekly_hrs_t_focal9 employed_focal9 housework_focal9 educ_focal9 earnings_t_focal9 NUM_CHILDREN_9 partnered9 TOTAL_INCOME_T_FAMILY9 i.raceth_fixed_focal birth_yr_all i.sample_type,
AGE_YOUNG_CHILD_10:       AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16           weekly_hrs_t_focal10 employed_focal10 housework_focal10 educ_focal10 earnings_t_focal10 NUM_CHILDREN_10 partnered10 TOTAL_INCOME_T_FAMILY10 i.raceth_fixed_focal birth_yr_all i.sample_type,
AGE_YOUNG_CHILD_11:      AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16            weekly_hrs_t_focal11 employed_focal11 housework_focal11 educ_focal11 earnings_t_focal11 NUM_CHILDREN_11 partnered11 TOTAL_INCOME_T_FAMILY11 i.raceth_fixed_focal birth_yr_all i.sample_type,
AGE_YOUNG_CHILD_12:     AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16             weekly_hrs_t_focal12 employed_focal12 housework_focal12 educ_focal12 earnings_t_focal12 NUM_CHILDREN_12 partnered12 TOTAL_INCOME_T_FAMILY12 i.raceth_fixed_focal birth_yr_all i.sample_type,
AGE_YOUNG_CHILD_13:    AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16              weekly_hrs_t_focal13 employed_focal13 housework_focal13 educ_focal13 earnings_t_focal13 NUM_CHILDREN_13 partnered13 TOTAL_INCOME_T_FAMILY13 i.raceth_fixed_focal birth_yr_all i.sample_type,
AGE_YOUNG_CHILD_14:   AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_15 AGE_YOUNG_CHILD_16               weekly_hrs_t_focal14 employed_focal14 housework_focal14 educ_focal14 earnings_t_focal14 NUM_CHILDREN_14 partnered14 TOTAL_INCOME_T_FAMILY14 i.raceth_fixed_focal birth_yr_all i.sample_type,
AGE_YOUNG_CHILD_15:  AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_16                weekly_hrs_t_focal15 employed_focal15 housework_focal15 educ_focal15 earnings_t_focal15 NUM_CHILDREN_15 partnered15 TOTAL_INCOME_T_FAMILY15 i.raceth_fixed_focal birth_yr_all i.sample_type,
AGE_YOUNG_CHILD_16: AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 AGE_YOUNG_CHILD_15                 weekly_hrs_t_focal16 employed_focal16 housework_focal16 educ_focal16 earnings_t_focal16 NUM_CHILDREN_16 partnered16 TOTAL_INCOME_T_FAMILY16 i.raceth_fixed_focal birth_yr_all i.sample_type,

/* Partnership Status */
partnered0:                 partnered1 partnered2 partnered3 partnered4 partnered5 partnered6 partnered7 partnered8 partnered9 partnered10 partnered11 partnered12 partnered13 partnered14 partnered15 partnered16 weekly_hrs_t_focal0 employed_focal0 housework_focal0 earnings_t_focal0 NUM_CHILDREN_0 AGE_YOUNG_CHILD_0 educ_focal0 TOTAL_INCOME_T_FAMILY0 i.raceth_fixed_focal birth_yr_all i.sample_type,
partnered1:                partnered0 partnered2 partnered3 partnered4 partnered5 partnered6 partnered7 partnered8 partnered9 partnered10 partnered11 partnered12 partnered13 partnered14 partnered15 partnered16  weekly_hrs_t_focal1 employed_focal1 housework_focal1 earnings_t_focal1 NUM_CHILDREN_1 AGE_YOUNG_CHILD_1 educ_focal1 TOTAL_INCOME_T_FAMILY1 i.raceth_fixed_focal birth_yr_all i.sample_type,
partnered2:               partnered0 partnered1 partnered3 partnered4 partnered5 partnered6 partnered7 partnered8 partnered9 partnered10 partnered11 partnered12 partnered13 partnered14 partnered15 partnered16   weekly_hrs_t_focal2 employed_focal2 housework_focal2 earnings_t_focal2 NUM_CHILDREN_2 AGE_YOUNG_CHILD_2 educ_focal2 TOTAL_INCOME_T_FAMILY2 i.raceth_fixed_focal birth_yr_all i.sample_type,
partnered3:              partnered0 partnered1 partnered2 partnered4 partnered5 partnered6 partnered7 partnered8 partnered9 partnered10 partnered11 partnered12 partnered13 partnered14 partnered15 partnered16    weekly_hrs_t_focal3 employed_focal3 housework_focal3 earnings_t_focal3 NUM_CHILDREN_3 AGE_YOUNG_CHILD_3 educ_focal3 TOTAL_INCOME_T_FAMILY3 i.raceth_fixed_focal birth_yr_all i.sample_type,
partnered4:             partnered0 partnered1 partnered2 partnered3 partnered5 partnered6 partnered7 partnered8 partnered9 partnered10 partnered11 partnered12 partnered13 partnered14 partnered15 partnered16     weekly_hrs_t_focal4 employed_focal4 housework_focal4 earnings_t_focal4 NUM_CHILDREN_4 AGE_YOUNG_CHILD_4 educ_focal4 TOTAL_INCOME_T_FAMILY4 i.raceth_fixed_focal birth_yr_all i.sample_type,
partnered5:            partnered0 partnered1 partnered2 partnered3 partnered4 partnered6 partnered7 partnered8 partnered9 partnered10 partnered11 partnered12 partnered13 partnered14 partnered15 partnered16      weekly_hrs_t_focal5 employed_focal5 housework_focal5 earnings_t_focal5 NUM_CHILDREN_5 AGE_YOUNG_CHILD_5 educ_focal5 TOTAL_INCOME_T_FAMILY5 i.raceth_fixed_focal birth_yr_all i.sample_type,
partnered6:           partnered0 partnered1 partnered2 partnered3 partnered4 partnered5 partnered7 partnered8 partnered9 partnered10 partnered11 partnered12 partnered13 partnered14 partnered15 partnered16       weekly_hrs_t_focal6 employed_focal6 housework_focal6 earnings_t_focal6 NUM_CHILDREN_6 AGE_YOUNG_CHILD_6 educ_focal6 TOTAL_INCOME_T_FAMILY6 i.raceth_fixed_focal birth_yr_all i.sample_type,
partnered7:          partnered0 partnered1 partnered2 partnered3 partnered4 partnered5 partnered6 partnered8 partnered9 partnered10 partnered11 partnered12 partnered13 partnered14 partnered15 partnered16        weekly_hrs_t_focal7 employed_focal7 housework_focal7 earnings_t_focal7 NUM_CHILDREN_7 AGE_YOUNG_CHILD_7 educ_focal7 TOTAL_INCOME_T_FAMILY7 i.raceth_fixed_focal birth_yr_all i.sample_type,
partnered8:         partnered0 partnered1 partnered2 partnered3 partnered4 partnered5 partnered6 partnered7 partnered9 partnered10 partnered11 partnered12 partnered13 partnered14 partnered15 partnered16         weekly_hrs_t_focal8 employed_focal8 housework_focal8 earnings_t_focal8 NUM_CHILDREN_8 AGE_YOUNG_CHILD_8 educ_focal8 TOTAL_INCOME_T_FAMILY8 i.raceth_fixed_focal birth_yr_all i.sample_type,
partnered9:        partnered0 partnered1 partnered2 partnered3 partnered4 partnered5 partnered6 partnered7 partnered8 partnered10 partnered11 partnered12 partnered13 partnered14 partnered15 partnered16          weekly_hrs_t_focal9 employed_focal9 housework_focal9 earnings_t_focal9 NUM_CHILDREN_9 AGE_YOUNG_CHILD_9 educ_focal9 TOTAL_INCOME_T_FAMILY9 i.raceth_fixed_focal birth_yr_all i.sample_type,
partnered10:       partnered0 partnered1 partnered2 partnered3 partnered4 partnered5 partnered6 partnered7 partnered8 partnered9 partnered11 partnered12 partnered13 partnered14 partnered15 partnered16           weekly_hrs_t_focal10 employed_focal10 housework_focal10 earnings_t_focal10 NUM_CHILDREN_10 AGE_YOUNG_CHILD_10 educ_focal10 TOTAL_INCOME_T_FAMILY10 i.raceth_fixed_focal birth_yr_all i.sample_type,
partnered11:      partnered0 partnered1 partnered2 partnered3 partnered4 partnered5 partnered6 partnered7 partnered8 partnered9 partnered10 partnered12 partnered13 partnered14 partnered15 partnered16            weekly_hrs_t_focal11 employed_focal11 housework_focal11 earnings_t_focal11 NUM_CHILDREN_11 AGE_YOUNG_CHILD_11 educ_focal11 TOTAL_INCOME_T_FAMILY11 i.raceth_fixed_focal birth_yr_all i.sample_type,
partnered12:     partnered0 partnered1 partnered2 partnered3 partnered4 partnered5 partnered6 partnered7 partnered8 partnered9 partnered10 partnered11 partnered13 partnered14 partnered15 partnered16             weekly_hrs_t_focal12 employed_focal12 housework_focal12 earnings_t_focal12 NUM_CHILDREN_12 AGE_YOUNG_CHILD_12 educ_focal12 TOTAL_INCOME_T_FAMILY12 i.raceth_fixed_focal birth_yr_all i.sample_type,
partnered13:    partnered0 partnered1 partnered2 partnered3 partnered4 partnered5 partnered6 partnered7 partnered8 partnered9 partnered10 partnered11 partnered12 partnered14 partnered15 partnered16              weekly_hrs_t_focal13 employed_focal13 housework_focal13 earnings_t_focal13 NUM_CHILDREN_13 AGE_YOUNG_CHILD_13 educ_focal13 TOTAL_INCOME_T_FAMILY13 i.raceth_fixed_focal birth_yr_all i.sample_type,
partnered14:   partnered0 partnered1 partnered2 partnered3 partnered4 partnered5 partnered6 partnered7 partnered8 partnered9 partnered10 partnered11 partnered12 partnered13 partnered15 partnered16               weekly_hrs_t_focal14 employed_focal14 housework_focal14 earnings_t_focal14 NUM_CHILDREN_14 AGE_YOUNG_CHILD_14 educ_focal14 TOTAL_INCOME_T_FAMILY14 i.raceth_fixed_focal birth_yr_all i.sample_type,
partnered15:  partnered0 partnered1 partnered2 partnered3 partnered4 partnered5 partnered6 partnered7 partnered8 partnered9 partnered10 partnered11 partnered12 partnered13 partnered14 partnered16                weekly_hrs_t_focal15 employed_focal15 housework_focal15 earnings_t_focal15 NUM_CHILDREN_15 AGE_YOUNG_CHILD_15 educ_focal15 TOTAL_INCOME_T_FAMILY15 i.raceth_fixed_focal birth_yr_all i.sample_type,
partnered16: partnered0 partnered1 partnered2 partnered3 partnered4 partnered5 partnered6 partnered7 partnered8 partnered9 partnered10 partnered11 partnered12 partnered13 partnered14 partnered15                 weekly_hrs_t_focal16 employed_focal16 housework_focal16 earnings_t_focal16 NUM_CHILDREN_16 AGE_YOUNG_CHILD_16 educ_focal16 TOTAL_INCOME_T_FAMILY16 i.raceth_fixed_focal birth_yr_all i.sample_type,

/* Total family income */
TOTAL_INCOME_T_FAMILY0:                 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16 weekly_hrs_t_focal0 employed_focal0 housework_focal0 educ_focal0 earnings_t_focal0 NUM_CHILDREN_0 partnered0 AGE_YOUNG_CHILD_0 i.raceth_fixed_focal birth_yr_all i.sample_type,
TOTAL_INCOME_T_FAMILY1:                TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16  weekly_hrs_t_focal1 employed_focal1 housework_focal1 educ_focal1 earnings_t_focal1 NUM_CHILDREN_1 partnered1 AGE_YOUNG_CHILD_1 i.raceth_fixed_focal birth_yr_all i.sample_type,
TOTAL_INCOME_T_FAMILY2:               TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16   weekly_hrs_t_focal2 employed_focal2 housework_focal2 educ_focal2 earnings_t_focal2 NUM_CHILDREN_2 partnered2 AGE_YOUNG_CHILD_2 i.raceth_fixed_focal birth_yr_all i.sample_type,
TOTAL_INCOME_T_FAMILY3:              TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16    weekly_hrs_t_focal3 employed_focal3 housework_focal3 educ_focal3 earnings_t_focal3 NUM_CHILDREN_3 partnered3 AGE_YOUNG_CHILD_3 i.raceth_fixed_focal birth_yr_all i.sample_type,
TOTAL_INCOME_T_FAMILY4:             TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16     weekly_hrs_t_focal4 employed_focal4 housework_focal4 educ_focal4 earnings_t_focal4 NUM_CHILDREN_4 partnered4 AGE_YOUNG_CHILD_4 i.raceth_fixed_focal birth_yr_all i.sample_type,
TOTAL_INCOME_T_FAMILY5:            TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16      weekly_hrs_t_focal5 employed_focal5 housework_focal5 educ_focal5 earnings_t_focal5 NUM_CHILDREN_5 partnered5 AGE_YOUNG_CHILD_5 i.raceth_fixed_focal birth_yr_all i.sample_type,
TOTAL_INCOME_T_FAMILY6:           TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16       weekly_hrs_t_focal6 employed_focal6 housework_focal6 educ_focal6 earnings_t_focal6 NUM_CHILDREN_6 partnered6 AGE_YOUNG_CHILD_6 i.raceth_fixed_focal birth_yr_all i.sample_type,
TOTAL_INCOME_T_FAMILY7:          TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16        weekly_hrs_t_focal7 employed_focal7 housework_focal7 educ_focal7 earnings_t_focal7 NUM_CHILDREN_7 partnered7 AGE_YOUNG_CHILD_7 i.raceth_fixed_focal birth_yr_all i.sample_type,
TOTAL_INCOME_T_FAMILY8:         TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16         weekly_hrs_t_focal8 employed_focal8 housework_focal8 educ_focal8 earnings_t_focal8 NUM_CHILDREN_8 partnered8 AGE_YOUNG_CHILD_8 i.raceth_fixed_focal birth_yr_all i.sample_type,
TOTAL_INCOME_T_FAMILY9:        TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16          weekly_hrs_t_focal9 employed_focal9 housework_focal9 educ_focal9 earnings_t_focal9 NUM_CHILDREN_9 partnered9 AGE_YOUNG_CHILD_9 i.raceth_fixed_focal birth_yr_all i.sample_type,
TOTAL_INCOME_T_FAMILY10:       TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16           weekly_hrs_t_focal10 employed_focal10 housework_focal10 educ_focal10 earnings_t_focal10 NUM_CHILDREN_10 partnered10 AGE_YOUNG_CHILD_10 i.raceth_fixed_focal birth_yr_all i.sample_type,
TOTAL_INCOME_T_FAMILY11:      TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16            weekly_hrs_t_focal11 employed_focal11 housework_focal11 educ_focal11 earnings_t_focal11 NUM_CHILDREN_11 partnered11 AGE_YOUNG_CHILD_11 i.raceth_fixed_focal birth_yr_all i.sample_type,
TOTAL_INCOME_T_FAMILY12:     TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16             weekly_hrs_t_focal12 employed_focal12 housework_focal12 educ_focal12 earnings_t_focal12 NUM_CHILDREN_12 partnered12 AGE_YOUNG_CHILD_12 i.raceth_fixed_focal birth_yr_all i.sample_type,
TOTAL_INCOME_T_FAMILY13:    TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16              weekly_hrs_t_focal13 employed_focal13 housework_focal13 educ_focal13 earnings_t_focal13 NUM_CHILDREN_13 partnered13 AGE_YOUNG_CHILD_13 i.raceth_fixed_focal birth_yr_all i.sample_type,
TOTAL_INCOME_T_FAMILY14:   TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T_FAMILY16               weekly_hrs_t_focal14 employed_focal14 housework_focal14 educ_focal14 earnings_t_focal14 NUM_CHILDREN_14 partnered14 AGE_YOUNG_CHILD_14 i.raceth_fixed_focal birth_yr_all i.sample_type,
TOTAL_INCOME_T_FAMILY15:  TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY16                weekly_hrs_t_focal15 employed_focal15 housework_focal15 educ_focal15 earnings_t_focal15 NUM_CHILDREN_15 partnered15 AGE_YOUNG_CHILD_15 i.raceth_fixed_focal birth_yr_all i.sample_type,
TOTAL_INCOME_T_FAMILY16: TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15                 weekly_hrs_t_focal16 employed_focal16 housework_focal16 educ_focal16 earnings_t_focal16 NUM_CHILDREN_16 partnered16 AGE_YOUNG_CHILD_16 i.raceth_fixed_focal birth_yr_all i.sample_type)

;
#delimit cr

use ice_test_bysex.dta, clear

mi import ice

mi reshape long in_sample_ relationship_  partnered weekly_hrs_t1_focal earnings_t1_focal housework_focal employed_focal educ_focal college_focal age_focal weekly_hrs_t2_focal earnings_t2_focal employed_t2_focal start_yr_employer_focal yrs_employer_focal children FAMILY_INTERVIEW_NUM_ NUM_CHILDREN_ AGE_YOUNG_CHILD_ TOTAL_INCOME_T1_FAMILY_ hours_type_t1_focal hw_hours_gp raceth_focal weekly_hrs_t_focal earnings_t_focal TOTAL_INCOME_T_FAMILY childcare_focal adultcare_focal TOTAL_INCOME_T2_FAMILY_ ///
, i(couple_id unique_id partner_id rel_start_all ) j(duration_rec) // _mi _mj

mi convert flong

browse couple_id unique_id partner_id SEX duration_rec weekly_hrs_t_focal housework_focal _mi_miss _mi_m _mi_id
gen imputed=0
replace imputed=1 if inrange(_mi_m,1,10)

inspect weekly_hrs_t_focal if imputed==0
inspect weekly_hrs_t_focal if imputed==1

inspect housework_focal if imputed==0
inspect housework_focal if imputed==1

// mi register regular n

save "$created_data/psid_individs_imputed_long_ice", replace

*******************************************************************************
*  Let's look at some descriptives
********************************************************************************
tabstat weekly_hrs_t_focal housework_focal, by(imputed) stats(mean sd p50)
tabstat weekly_hrs_t_focal housework_focal if SEX==1, by(imputed) stats(mean sd p50)
tabstat weekly_hrs_t_focal housework_focal if SEX==2, by(imputed) stats(mean sd p50)

tabstat weekly_hrs_t_focal housework_focal childcare_focal adultcare_focal employed_focal earnings_t_focal age_focal birth_yr_all educ_focal college_focal raceth_focal raceth_fixed_focal children NUM_CHILDREN_ FIRST_BIRTH_YR AGE_YOUNG_CHILD_ relationship_ partnered TOTAL_INCOME_T_FAMILY sample_type if imputed==0, stats(mean sd p50) columns(statistics)

tabstat weekly_hrs_t_focal housework_focal childcare_focal adultcare_focal employed_focal earnings_t_focal age_focal birth_yr_all educ_focal college_focal raceth_focal raceth_fixed_focal children NUM_CHILDREN_ FIRST_BIRTH_YR AGE_YOUNG_CHILD_ relationship_ partnered TOTAL_INCOME_T_FAMILY sample_type if imputed==1, stats(mean sd p50) columns(statistics)

histogram weekly_hrs_t_focal, width(1)
twoway (histogram weekly_hrs_t_focal if imputed==0, width(2) color(blue%30)) (histogram weekly_hrs_t_focal if imputed==1, width(2) color(red%30)), legend(order(1 "Observed" 2 "Imputed") rows(1) position(6)) xtitle("Weekly Employment Hours")
twoway (histogram weekly_hrs_t_focal if imputed==0 & SEX==1, width(2) color(blue%30)) (histogram weekly_hrs_t_focal if imputed==1 & SEX==1, width(2) color(red%30)), legend(order(1 "Observed" 2 "Imputed") rows(1) position(6))
twoway (histogram weekly_hrs_t_focal if imputed==0 & SEX==2, width(2) color(blue%30)) (histogram weekly_hrs_t_focal if imputed==1 & SEX==2, width(2) color(red%30)), legend(order(1 "Observed" 2 "Imputed") rows(1) position(6))

histogram weekly_hrs_t_focal if weekly_hrs_t1_focal>0, width(1)
histogram housework_focal, width(1)
twoway (histogram housework_focal if imputed==0, width(2) color(blue%30)) (histogram housework_focal if imputed==1, width(2) color(red%30)), legend(order(1 "Observed" 2 "Imputed") rows(1) position(6)) xtitle("Weekly Housework Hours")

preserve

collapse (mean) weekly_hrs_t_focal housework_focal, by(duration_rec imputed)

twoway (line weekly_hrs_t_focal duration_rec if imputed==0) (line weekly_hrs_t_focal duration_rec if imputed==1), legend(order(1 "Observed" 2 "Imputed") rows(1) position(6)) ytitle("Weekly Employment Hours") title("Avg Employment Hours by Duration") xtitle("Marital Duration")
twoway (line housework_focal duration_rec if imputed==0) (line housework_focal duration_rec if imputed==1), legend(order(1 "Observed" 2 "Imputed") rows(1) position(6)) ytitle("Weekly Housework Hours") title("Avg Housework Hours by Duration") xtitle("Marital Duration")

restore

//
preserve

collapse (mean) weekly_hrs_t_focal housework_focal, by(SEX duration_rec imputed)

// men
twoway (line weekly_hrs_t_focal duration_rec if imputed==0 & SEX==1) (line weekly_hrs_t_focal duration_rec if imputed==1 & SEX==1), legend(order(1 "Observed" 2 "Imputed") rows(1) position(6))
twoway (line housework_focal duration_rec if imputed==0 & SEX==1) (line housework_focal duration_rec if imputed==1 & SEX==1), legend(order(1 "Observed" 2 "Imputed") rows(1) position(6))

// women - okay so it is women where the disparities are primarily. is it bc of EMPLOYMENT STATUS?! need to do conditional on that? let's see if it improves with other predictors, bc employment status not currently included
twoway (line weekly_hrs_t_focal duration_rec if imputed==0 & SEX==2) (line weekly_hrs_t_focal duration_rec if imputed==1 & SEX==2), legend(order(1 "Observed" 2 "Imputed") rows(1) position(6))
twoway (line housework_focal duration_rec if imputed==0 & SEX==2) (line housework_focal duration_rec if imputed==1 & SEX==2), legend(order(1 "Observed" 2 "Imputed") rows(1) position(6))

restore
