********************************************************************************
* This is the imputation that we used previously before:
* a. changing the sample (more relationships based on start dates within 3 years of last wave)
* b. adding 2023
* c. adding new variables
********************************************************************************

use "$created_data/individs_by_duration_wide.dta", clear

egen nmis_age = rmiss(age_focal*)
tab nmis_age, m

drop if nmis_age==15 // for now, just so this is actually complete
drop if birth_yr_all==. // for now, just so this is actually complete
drop if raceth_fixed_focal==. // for now, just so this is actually complete
drop if fixed_education==.

mi set wide
mi register imputed weekly_hrs_t_focal* housework_focal* employed_focal* earnings_t_focal* children* NUM_CHILDREN_* AGE_YOUNG_CHILD_* relationship_* partnered* TOTAL_INCOME_T_FAMILY* num_children_imp_hh* // to add (May 2025) (need to add to Excel): disabled_focal sr_health_focal num_65up_hh lives_with_parent (possibly recode: lives with parent OR grandparent)
mi register regular FIRST_BIRTH_YR birth_yr_all rel_start_all SEX raceth_fixed_focal sample_type rel_type_constant fixed_education // considering adding (May 2025): ever_parent_focal num_births_focal (these are time *constant*) birth_timing_rel (or recode so it's like pre-v.post-marital) current_rel_number_main retired_est_focal* (use as time-varying but no need to impute)
// swap rel_status for rel_type_constant?

// log using "$logdir\mi_education_help.log", replace

// start imputation
#delimit ;

mi impute chained

/* Employment hours */
(pmm, knn(5) include (              weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 housework_focal0 earnings_t_focal0 num_children_imp_hh0 AGE_YOUNG_CHILD_0 i.partnered_imp0 TOTAL_INCOME_T_FAMILY0)) weekly_hrs_t_focal0
(pmm, knn(5) include (             weekly_hrs_t_focal0 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14  housework_focal1 earnings_t_focal1 num_children_imp_hh1 AGE_YOUNG_CHILD_1 i.partnered_imp1 TOTAL_INCOME_T_FAMILY1)) weekly_hrs_t_focal1
(pmm, knn(5) include (            weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14   housework_focal2 earnings_t_focal2 num_children_imp_hh2 AGE_YOUNG_CHILD_2 i.partnered_imp2 TOTAL_INCOME_T_FAMILY2)) weekly_hrs_t_focal2
(pmm, knn(5) include (           weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14    housework_focal3 earnings_t_focal3 num_children_imp_hh3 AGE_YOUNG_CHILD_3 i.partnered_imp3 TOTAL_INCOME_T_FAMILY3)) weekly_hrs_t_focal3
(pmm, knn(5) include (          weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14     housework_focal4 earnings_t_focal4 num_children_imp_hh4 AGE_YOUNG_CHILD_4 i.partnered_imp4 TOTAL_INCOME_T_FAMILY4)) weekly_hrs_t_focal4
(pmm, knn(5) include (         weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14      housework_focal5 earnings_t_focal5 num_children_imp_hh5 AGE_YOUNG_CHILD_5 i.partnered_imp5 TOTAL_INCOME_T_FAMILY5)) weekly_hrs_t_focal5
(pmm, knn(5) include (        weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14       housework_focal6 earnings_t_focal6 num_children_imp_hh6 AGE_YOUNG_CHILD_6 i.partnered_imp6 TOTAL_INCOME_T_FAMILY6)) weekly_hrs_t_focal6
(pmm, knn(5) include (       weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14        housework_focal7 earnings_t_focal7 num_children_imp_hh7 AGE_YOUNG_CHILD_7 i.partnered_imp7 TOTAL_INCOME_T_FAMILY7)) weekly_hrs_t_focal7
(pmm, knn(5) include (      weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14         housework_focal8 earnings_t_focal8 num_children_imp_hh8 AGE_YOUNG_CHILD_8 i.partnered_imp8 TOTAL_INCOME_T_FAMILY8)) weekly_hrs_t_focal8
(pmm, knn(5) include (     weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14          housework_focal9 earnings_t_focal9 num_children_imp_hh9 AGE_YOUNG_CHILD_9 i.partnered_imp9 TOTAL_INCOME_T_FAMILY9)) weekly_hrs_t_focal9
(pmm, knn(5) include (    weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14           housework_focal10 earnings_t_focal10 num_children_imp_hh10 AGE_YOUNG_CHILD_10 i.partnered_imp10 TOTAL_INCOME_T_FAMILY10)) weekly_hrs_t_focal10
(pmm, knn(5) include (   weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14            housework_focal11 earnings_t_focal11 num_children_imp_hh11 AGE_YOUNG_CHILD_11 i.partnered_imp11 TOTAL_INCOME_T_FAMILY11)) weekly_hrs_t_focal11
(pmm, knn(5) include (  weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal13 weekly_hrs_t_focal14             housework_focal12 earnings_t_focal12 num_children_imp_hh12 AGE_YOUNG_CHILD_12 i.partnered_imp12 TOTAL_INCOME_T_FAMILY12)) weekly_hrs_t_focal12
(pmm, knn(5) include ( weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal14              housework_focal13 earnings_t_focal13 num_children_imp_hh13 AGE_YOUNG_CHILD_13 i.partnered_imp13 TOTAL_INCOME_T_FAMILY13)) weekly_hrs_t_focal13
(pmm, knn(5) include (weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13               housework_focal14 earnings_t_focal14 num_children_imp_hh14 AGE_YOUNG_CHILD_14 i.partnered_imp14 TOTAL_INCOME_T_FAMILY14)) weekly_hrs_t_focal14


/* Housework Hours */
(pmm, knn(5) include (              housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 weekly_hrs_t_focal0 earnings_t_focal0 num_children_imp_hh0 AGE_YOUNG_CHILD_0 i.partnered_imp0 TOTAL_INCOME_T_FAMILY0)) housework_focal0
(pmm, knn(5) include (             housework_focal0 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14  weekly_hrs_t_focal1 earnings_t_focal1 num_children_imp_hh1 AGE_YOUNG_CHILD_1 i.partnered_imp1 TOTAL_INCOME_T_FAMILY1)) housework_focal1
(pmm, knn(5) include (            housework_focal0 housework_focal1 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14   weekly_hrs_t_focal2 earnings_t_focal2 num_children_imp_hh2 AGE_YOUNG_CHILD_2 i.partnered_imp2 TOTAL_INCOME_T_FAMILY2)) housework_focal2
(pmm, knn(5) include (           housework_focal0 housework_focal1 housework_focal2 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14    weekly_hrs_t_focal3 earnings_t_focal3 num_children_imp_hh3 AGE_YOUNG_CHILD_3 i.partnered_imp3 TOTAL_INCOME_T_FAMILY3)) housework_focal3
(pmm, knn(5) include (          housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14     weekly_hrs_t_focal4 earnings_t_focal4 num_children_imp_hh4 AGE_YOUNG_CHILD_4 i.partnered_imp4 TOTAL_INCOME_T_FAMILY4)) housework_focal4
(pmm, knn(5) include (         housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14      weekly_hrs_t_focal5 earnings_t_focal5 num_children_imp_hh5 AGE_YOUNG_CHILD_5 i.partnered_imp5 TOTAL_INCOME_T_FAMILY5)) housework_focal5
(pmm, knn(5) include (        housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14       weekly_hrs_t_focal6 earnings_t_focal6 num_children_imp_hh6 AGE_YOUNG_CHILD_6 i.partnered_imp6 TOTAL_INCOME_T_FAMILY6)) housework_focal6
(pmm, knn(5) include (       housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14        weekly_hrs_t_focal7 earnings_t_focal7 num_children_imp_hh7 AGE_YOUNG_CHILD_7 i.partnered_imp7 TOTAL_INCOME_T_FAMILY7)) housework_focal7
(pmm, knn(5) include (      housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14         weekly_hrs_t_focal8 earnings_t_focal8 num_children_imp_hh8 AGE_YOUNG_CHILD_8 i.partnered_imp8 TOTAL_INCOME_T_FAMILY8)) housework_focal8
(pmm, knn(5) include (     housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14          weekly_hrs_t_focal9 earnings_t_focal9 num_children_imp_hh9 AGE_YOUNG_CHILD_9 i.partnered_imp9 TOTAL_INCOME_T_FAMILY9)) housework_focal9
(pmm, knn(5) include (    housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal11 housework_focal12 housework_focal13 housework_focal14           weekly_hrs_t_focal10 earnings_t_focal10 num_children_imp_hh10 AGE_YOUNG_CHILD_10 i.partnered_imp10 TOTAL_INCOME_T_FAMILY10)) housework_focal10
(pmm, knn(5) include (   housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal12 housework_focal13 housework_focal14            weekly_hrs_t_focal11 earnings_t_focal11 num_children_imp_hh11 AGE_YOUNG_CHILD_11 i.partnered_imp11 TOTAL_INCOME_T_FAMILY11)) housework_focal11
(pmm, knn(5) include (  housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal13 housework_focal14             weekly_hrs_t_focal12 earnings_t_focal12 num_children_imp_hh12 AGE_YOUNG_CHILD_12 i.partnered_imp12 TOTAL_INCOME_T_FAMILY12)) housework_focal12
(pmm, knn(5) include ( housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal14              weekly_hrs_t_focal13 earnings_t_focal13 num_children_imp_hh13 AGE_YOUNG_CHILD_13 i.partnered_imp13 TOTAL_INCOME_T_FAMILY13)) housework_focal13
(pmm, knn(5) include (housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13               weekly_hrs_t_focal14 earnings_t_focal14 num_children_imp_hh14 AGE_YOUNG_CHILD_14 i.partnered_imp14 TOTAL_INCOME_T_FAMILY14)) housework_focal14

/*
/* Employment Status */
(logit, include (              i.employed_focal1 i.employed_focal2 i.employed_focal3 i.employed_focal4 i.employed_focal5 i.employed_focal6 i.employed_focal7 i.employed_focal8 i.employed_focal9 i.employed_focal10 i.employed_focal11 i.employed_focal12 i.employed_focal13 i.employed_focal14  housework_focal0  i.educ_focal_imp0 num_children_imp0 AGE_YOUNG_CHILD_0 i.partnered_imp0 TOTAL_INCOME_T_FAMILY0)) employed_focal0
(logit, include (             i.employed_focal0 i.employed_focal2 i.employed_focal3 i.employed_focal4 i.employed_focal5 i.employed_focal6 i.employed_focal7 i.employed_focal8 i.employed_focal9 i.employed_focal10 i.employed_focal11 i.employed_focal12 i.employed_focal13 i.employed_focal14  weekly_hrs_t_focal0 housework_focal1 earnings_t_focal0 i.educ_focal_imp1 num_children_imp1 AGE_YOUNG_CHILD_1 i.partnered_imp1 TOTAL_INCOME_T_FAMILY1)) employed_focal1
(logit, include (            i.employed_focal0 i.employed_focal1 i.employed_focal3 i.employed_focal4 i.employed_focal5 i.employed_focal6 i.employed_focal7 i.employed_focal8 i.employed_focal9 i.employed_focal10 i.employed_focal11 i.employed_focal12 i.employed_focal13 i.employed_focal14   weekly_hrs_t_focal1 housework_focal2 earnings_t_focal1 i.educ_focal_imp2 num_children_imp2 AGE_YOUNG_CHILD_2 i.partnered_imp2 TOTAL_INCOME_T_FAMILY2)) employed_focal2
(logit, include (           i.employed_focal0 i.employed_focal1 i.employed_focal2 i.employed_focal4 i.employed_focal5 i.employed_focal6 i.employed_focal7 i.employed_focal8 i.employed_focal9 i.employed_focal10 i.employed_focal11 i.employed_focal12 i.employed_focal13 i.employed_focal14    weekly_hrs_t_focal2 housework_focal3 earnings_t_focal2 i.educ_focal_imp3 num_children_imp3 AGE_YOUNG_CHILD_3 i.partnered_imp3 TOTAL_INCOME_T_FAMILY3)) employed_focal3
(logit, include (          i.employed_focal0 i.employed_focal1 i.employed_focal2 i.employed_focal3 i.employed_focal5 i.employed_focal6 i.employed_focal7 i.employed_focal8 i.employed_focal9 i.employed_focal10 i.employed_focal11 i.employed_focal12 i.employed_focal13 i.employed_focal14     weekly_hrs_t_focal3 housework_focal4 earnings_t_focal3 i.educ_focal_imp4 num_children_imp4 AGE_YOUNG_CHILD_4 i.partnered_imp4 TOTAL_INCOME_T_FAMILY4)) employed_focal4
(logit, include (         i.employed_focal0 i.employed_focal1 i.employed_focal2 i.employed_focal3 i.employed_focal4 i.employed_focal6 i.employed_focal7 i.employed_focal8 i.employed_focal9 i.employed_focal10 i.employed_focal11 i.employed_focal12 i.employed_focal13 i.employed_focal14      weekly_hrs_t_focal4 housework_focal5 earnings_t_focal4 i.educ_focal_imp5 num_children_imp5 AGE_YOUNG_CHILD_5 i.partnered_imp5 TOTAL_INCOME_T_FAMILY5)) employed_focal5
(logit, include (        i.employed_focal0 i.employed_focal1 i.employed_focal2 i.employed_focal3 i.employed_focal4 i.employed_focal5 i.employed_focal7 i.employed_focal8 i.employed_focal9 i.employed_focal10 i.employed_focal11 i.employed_focal12 i.employed_focal13 i.employed_focal14       weekly_hrs_t_focal5 housework_focal6 earnings_t_focal5 i.educ_focal_imp6 num_children_imp6 AGE_YOUNG_CHILD_6 i.partnered_imp6 TOTAL_INCOME_T_FAMILY6)) employed_focal6
(logit, include (       i.employed_focal0 i.employed_focal1 i.employed_focal2 i.employed_focal3 i.employed_focal4 i.employed_focal5 i.employed_focal6 i.employed_focal8 i.employed_focal9 i.employed_focal10 i.employed_focal11 i.employed_focal12 i.employed_focal13 i.employed_focal14        weekly_hrs_t_focal6 housework_focal7 earnings_t_focal6 i.educ_focal_imp7 num_children_imp7 AGE_YOUNG_CHILD_7 i.partnered_imp7 TOTAL_INCOME_T_FAMILY7)) employed_focal7
(logit, include (      i.employed_focal0 i.employed_focal1 i.employed_focal2 i.employed_focal3 i.employed_focal4 i.employed_focal5 i.employed_focal6 i.employed_focal7 i.employed_focal9 i.employed_focal10 i.employed_focal11 i.employed_focal12 i.employed_focal13 i.employed_focal14         weekly_hrs_t_focal7 housework_focal8 earnings_t_focal7 i.educ_focal_imp8 num_children_imp8 AGE_YOUNG_CHILD_8 i.partnered_imp8 TOTAL_INCOME_T_FAMILY8)) employed_focal8
(logit, include (     i.employed_focal0 i.employed_focal1 i.employed_focal2 i.employed_focal3 i.employed_focal4 i.employed_focal5 i.employed_focal6 i.employed_focal7 i.employed_focal8 i.employed_focal10 i.employed_focal11 i.employed_focal12 i.employed_focal13 i.employed_focal14          weekly_hrs_t_focal8 housework_focal9 earnings_t_focal8 i.educ_focal_imp9 num_children_imp9 AGE_YOUNG_CHILD_9 i.partnered_imp9 TOTAL_INCOME_T_FAMILY9)) employed_focal9
(logit, include (    i.employed_focal0 i.employed_focal1 i.employed_focal2 i.employed_focal3 i.employed_focal4 i.employed_focal5 i.employed_focal6 i.employed_focal7 i.employed_focal8 i.employed_focal9 i.employed_focal11 i.employed_focal12 i.employed_focal13 i.employed_focal14           weekly_hrs_t_focal9 housework_focal10 earnings_t_focal9 i.educ_focal_imp10 num_children_imp10 AGE_YOUNG_CHILD_10 i.partnered_imp10 TOTAL_INCOME_T_FAMILY10)) employed_focal10
(logit, include (   i.employed_focal0 i.employed_focal1 i.employed_focal2 i.employed_focal3 i.employed_focal4 i.employed_focal5 i.employed_focal6 i.employed_focal7 i.employed_focal8 i.employed_focal9 i.employed_focal10 i.employed_focal12 i.employed_focal13 i.employed_focal14            weekly_hrs_t_focal10 housework_focal11 earnings_t_focal10 i.educ_focal_imp11 num_children_imp11 AGE_YOUNG_CHILD_11 i.partnered_imp11 TOTAL_INCOME_T_FAMILY11)) employed_focal11
(logit, include (  i.employed_focal0 i.employed_focal1 i.employed_focal2 i.employed_focal3 i.employed_focal4 i.employed_focal5 i.employed_focal6 i.employed_focal7 i.employed_focal8 i.employed_focal9 i.employed_focal10 i.employed_focal11 i.employed_focal13 i.employed_focal14             weekly_hrs_t_focal11 housework_focal12 earnings_t_focal11 i.educ_focal_imp12 num_children_imp12 AGE_YOUNG_CHILD_12 i.partnered_imp12 TOTAL_INCOME_T_FAMILY12)) employed_focal12
(logit, include ( i.employed_focal0 i.employed_focal1 i.employed_focal2 i.employed_focal3 i.employed_focal4 i.employed_focal5 i.employed_focal6 i.employed_focal7 i.employed_focal8 i.employed_focal9 i.employed_focal10 i.employed_focal11 i.employed_focal12 i.employed_focal14              weekly_hrs_t_focal12 housework_focal13 earnings_t_focal12 i.educ_focal_imp13 num_children_imp13 AGE_YOUNG_CHILD_13 i.partnered_imp13 TOTAL_INCOME_T_FAMILY13)) employed_focal13
(logit, include (i.employed_focal0 i.employed_focal1 i.employed_focal2 i.employed_focal3 i.employed_focal4 i.employed_focal5 i.employed_focal6 i.employed_focal7 i.employed_focal8 i.employed_focal9 i.employed_focal10 i.employed_focal11 i.employed_focal12 i.employed_focal13               weekly_hrs_t_focal13 housework_focal14 earnings_t_focal13 i.educ_focal_imp14 num_children_imp14 AGE_YOUNG_CHILD_14 i.partnered_imp14 TOTAL_INCOME_T_FAMILY14)) employed_focal14
*/

/* Annual Earnings */
(pmm, knn(5) include (              earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 weekly_hrs_t_focal0 housework_focal0 num_children_imp_hh0 AGE_YOUNG_CHILD_0 i.partnered_imp0 TOTAL_INCOME_T_FAMILY0)) earnings_t_focal0
(pmm, knn(5) include (             earnings_t_focal0 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14  weekly_hrs_t_focal1 housework_focal1 num_children_imp_hh1 AGE_YOUNG_CHILD_1 i.partnered_imp1 TOTAL_INCOME_T_FAMILY1)) earnings_t_focal1
(pmm, knn(5) include (            earnings_t_focal0 earnings_t_focal1 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14   weekly_hrs_t_focal2 housework_focal2 num_children_imp_hh2 AGE_YOUNG_CHILD_2 i.partnered_imp2 TOTAL_INCOME_T_FAMILY2)) earnings_t_focal2
(pmm, knn(5) include (           earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14    weekly_hrs_t_focal3 housework_focal3 num_children_imp_hh3 AGE_YOUNG_CHILD_3 i.partnered_imp3 TOTAL_INCOME_T_FAMILY3)) earnings_t_focal3
(pmm, knn(5) include (          earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14     weekly_hrs_t_focal4 housework_focal4 num_children_imp_hh4 AGE_YOUNG_CHILD_4 i.partnered_imp4 TOTAL_INCOME_T_FAMILY4)) earnings_t_focal4
(pmm, knn(5) include (         earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14      weekly_hrs_t_focal5 housework_focal5 num_children_imp_hh5 AGE_YOUNG_CHILD_5 i.partnered_imp5 TOTAL_INCOME_T_FAMILY5)) earnings_t_focal5
(pmm, knn(5) include (        earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14       weekly_hrs_t_focal6 housework_focal6 num_children_imp_hh6 AGE_YOUNG_CHILD_6 i.partnered_imp6 TOTAL_INCOME_T_FAMILY6)) earnings_t_focal6
(pmm, knn(5) include (       earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14        weekly_hrs_t_focal7 housework_focal7 num_children_imp_hh7 AGE_YOUNG_CHILD_7 i.partnered_imp7 TOTAL_INCOME_T_FAMILY7)) earnings_t_focal7
(pmm, knn(5) include (      earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14         weekly_hrs_t_focal8 housework_focal8 num_children_imp_hh8 AGE_YOUNG_CHILD_8 i.partnered_imp8 TOTAL_INCOME_T_FAMILY8)) earnings_t_focal8
(pmm, knn(5) include (     earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14          weekly_hrs_t_focal9 housework_focal9 num_children_imp_hh9 AGE_YOUNG_CHILD_9 i.partnered_imp9 TOTAL_INCOME_T_FAMILY9)) earnings_t_focal9
(pmm, knn(5) include (    earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14           weekly_hrs_t_focal10 housework_focal10 num_children_imp_hh10 AGE_YOUNG_CHILD_10 i.partnered_imp10 TOTAL_INCOME_T_FAMILY10)) earnings_t_focal10
(pmm, knn(5) include (   earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14            weekly_hrs_t_focal11 housework_focal11 num_children_imp_hh11 AGE_YOUNG_CHILD_11 i.partnered_imp11 TOTAL_INCOME_T_FAMILY11)) earnings_t_focal11
(pmm, knn(5) include (  earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal13 earnings_t_focal14             weekly_hrs_t_focal12 housework_focal12 num_children_imp_hh12 AGE_YOUNG_CHILD_12 i.partnered_imp12 TOTAL_INCOME_T_FAMILY12)) earnings_t_focal12
(pmm, knn(5) include ( earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal14              weekly_hrs_t_focal13 housework_focal13 num_children_imp_hh13 AGE_YOUNG_CHILD_13 i.partnered_imp13 TOTAL_INCOME_T_FAMILY13)) earnings_t_focal13
(pmm, knn(5) include (earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13               weekly_hrs_t_focal14 housework_focal14 num_children_imp_hh14 AGE_YOUNG_CHILD_14 i.partnered_imp14 TOTAL_INCOME_T_FAMILY14)) earnings_t_focal14

/* Educational Attainment - using time invariant now */

/* Number of Children */
(pmm, knn(5) include (              num_children_imp_hh1 num_children_imp_hh2 num_children_imp_hh3 num_children_imp_hh4 num_children_imp_hh5 num_children_imp_hh6 num_children_imp_hh7 num_children_imp_hh8 num_children_imp_hh9 num_children_imp_hh10 num_children_imp_hh11 num_children_imp_hh12 num_children_imp_hh13 num_children_imp_hh14 weekly_hrs_t_focal0 housework_focal0 earnings_t_focal0 AGE_YOUNG_CHILD_0 i.partnered_imp0 TOTAL_INCOME_T_FAMILY0)) num_children_imp_hh0
(pmm, knn(5) include (             num_children_imp_hh0 num_children_imp_hh2 num_children_imp_hh3 num_children_imp_hh4 num_children_imp_hh5 num_children_imp_hh6 num_children_imp_hh7 num_children_imp_hh8 num_children_imp_hh9 num_children_imp_hh10 num_children_imp_hh11 num_children_imp_hh12 num_children_imp_hh13 num_children_imp_hh14  weekly_hrs_t_focal1 housework_focal1 earnings_t_focal1 AGE_YOUNG_CHILD_1 i.partnered_imp1 TOTAL_INCOME_T_FAMILY1)) num_children_imp_hh1
(pmm, knn(5) include (            num_children_imp_hh0 num_children_imp_hh1 num_children_imp_hh3 num_children_imp_hh4 num_children_imp_hh5 num_children_imp_hh6 num_children_imp_hh7 num_children_imp_hh8 num_children_imp_hh9 num_children_imp_hh10 num_children_imp_hh11 num_children_imp_hh12 num_children_imp_hh13 num_children_imp_hh14   weekly_hrs_t_focal2 housework_focal2 earnings_t_focal2 AGE_YOUNG_CHILD_2 i.partnered_imp2 TOTAL_INCOME_T_FAMILY2)) num_children_imp_hh2
(pmm, knn(5) include (           num_children_imp_hh0 num_children_imp_hh1 num_children_imp_hh2 num_children_imp_hh4 num_children_imp_hh5 num_children_imp_hh6 num_children_imp_hh7 num_children_imp_hh8 num_children_imp_hh9 num_children_imp_hh10 num_children_imp_hh11 num_children_imp_hh12 num_children_imp_hh13 num_children_imp_hh14    weekly_hrs_t_focal3 housework_focal3 earnings_t_focal3 AGE_YOUNG_CHILD_3 i.partnered_imp3 TOTAL_INCOME_T_FAMILY3)) num_children_imp_hh3
(pmm, knn(5) include (          num_children_imp_hh0 num_children_imp_hh1 num_children_imp_hh2 num_children_imp_hh3 num_children_imp_hh5 num_children_imp_hh6 num_children_imp_hh7 num_children_imp_hh8 num_children_imp_hh9 num_children_imp_hh10 num_children_imp_hh11 num_children_imp_hh12 num_children_imp_hh13 num_children_imp_hh14     weekly_hrs_t_focal4 housework_focal4 earnings_t_focal4 AGE_YOUNG_CHILD_4 i.partnered_imp4 TOTAL_INCOME_T_FAMILY4)) num_children_imp_hh4
(pmm, knn(5) include (         num_children_imp_hh0 num_children_imp_hh1 num_children_imp_hh2 num_children_imp_hh3 num_children_imp_hh4 num_children_imp_hh6 num_children_imp_hh7 num_children_imp_hh8 num_children_imp_hh9 num_children_imp_hh10 num_children_imp_hh11 num_children_imp_hh12 num_children_imp_hh13 num_children_imp_hh14      weekly_hrs_t_focal5 housework_focal5 earnings_t_focal5 AGE_YOUNG_CHILD_5 i.partnered_imp5 TOTAL_INCOME_T_FAMILY5)) num_children_imp_hh5
(pmm, knn(5) include (        num_children_imp_hh0 num_children_imp_hh1 num_children_imp_hh2 num_children_imp_hh3 num_children_imp_hh4 num_children_imp_hh5 num_children_imp_hh7 num_children_imp_hh8 num_children_imp_hh9 num_children_imp_hh10 num_children_imp_hh11 num_children_imp_hh12 num_children_imp_hh13 num_children_imp_hh14       weekly_hrs_t_focal6 housework_focal6 earnings_t_focal6 AGE_YOUNG_CHILD_6 i.partnered_imp6 TOTAL_INCOME_T_FAMILY6)) num_children_imp_hh6
(pmm, knn(5) include (       num_children_imp_hh0 num_children_imp_hh1 num_children_imp_hh2 num_children_imp_hh3 num_children_imp_hh4 num_children_imp_hh5 num_children_imp_hh6 num_children_imp_hh8 num_children_imp_hh9 num_children_imp_hh10 num_children_imp_hh11 num_children_imp_hh12 num_children_imp_hh13 num_children_imp_hh14        weekly_hrs_t_focal7 housework_focal7 earnings_t_focal7 AGE_YOUNG_CHILD_7 i.partnered_imp7 TOTAL_INCOME_T_FAMILY7)) num_children_imp_hh7
(pmm, knn(5) include (      num_children_imp_hh0 num_children_imp_hh1 num_children_imp_hh2 num_children_imp_hh3 num_children_imp_hh4 num_children_imp_hh5 num_children_imp_hh6 num_children_imp_hh7 num_children_imp_hh9 num_children_imp_hh10 num_children_imp_hh11 num_children_imp_hh12 num_children_imp_hh13 num_children_imp_hh14         weekly_hrs_t_focal8 housework_focal8 earnings_t_focal8 AGE_YOUNG_CHILD_8 i.partnered_imp8 TOTAL_INCOME_T_FAMILY8)) num_children_imp_hh8
(pmm, knn(5) include (     num_children_imp_hh0 num_children_imp_hh1 num_children_imp_hh2 num_children_imp_hh3 num_children_imp_hh4 num_children_imp_hh5 num_children_imp_hh6 num_children_imp_hh7 num_children_imp_hh8 num_children_imp_hh10 num_children_imp_hh11 num_children_imp_hh12 num_children_imp_hh13 num_children_imp_hh14          weekly_hrs_t_focal9 housework_focal9 earnings_t_focal9 AGE_YOUNG_CHILD_9 i.partnered_imp9 TOTAL_INCOME_T_FAMILY9)) num_children_imp_hh9
(pmm, knn(5) include (    num_children_imp_hh0 num_children_imp_hh1 num_children_imp_hh2 num_children_imp_hh3 num_children_imp_hh4 num_children_imp_hh5 num_children_imp_hh6 num_children_imp_hh7 num_children_imp_hh8 num_children_imp_hh9 num_children_imp_hh11 num_children_imp_hh12 num_children_imp_hh13 num_children_imp_hh14           weekly_hrs_t_focal10 housework_focal10 earnings_t_focal10 AGE_YOUNG_CHILD_10 i.partnered_imp10 TOTAL_INCOME_T_FAMILY10)) num_children_imp_hh10
(pmm, knn(5) include (   num_children_imp_hh0 num_children_imp_hh1 num_children_imp_hh2 num_children_imp_hh3 num_children_imp_hh4 num_children_imp_hh5 num_children_imp_hh6 num_children_imp_hh7 num_children_imp_hh8 num_children_imp_hh9 num_children_imp_hh10 num_children_imp_hh12 num_children_imp_hh13 num_children_imp_hh14            weekly_hrs_t_focal11 housework_focal11 earnings_t_focal11 AGE_YOUNG_CHILD_11 i.partnered_imp11 TOTAL_INCOME_T_FAMILY11)) num_children_imp_hh11
(pmm, knn(5) include (  num_children_imp_hh0 num_children_imp_hh1 num_children_imp_hh2 num_children_imp_hh3 num_children_imp_hh4 num_children_imp_hh5 num_children_imp_hh6 num_children_imp_hh7 num_children_imp_hh8 num_children_imp_hh9 num_children_imp_hh10 num_children_imp_hh11 num_children_imp_hh13 num_children_imp_hh14             weekly_hrs_t_focal12 housework_focal12 earnings_t_focal12 AGE_YOUNG_CHILD_12 i.partnered_imp12 TOTAL_INCOME_T_FAMILY12)) num_children_imp_hh12
(pmm, knn(5) include ( num_children_imp_hh0 num_children_imp_hh1 num_children_imp_hh2 num_children_imp_hh3 num_children_imp_hh4 num_children_imp_hh5 num_children_imp_hh6 num_children_imp_hh7 num_children_imp_hh8 num_children_imp_hh9 num_children_imp_hh10 num_children_imp_hh11 num_children_imp_hh12 num_children_imp_hh14              weekly_hrs_t_focal13 housework_focal13 earnings_t_focal13 AGE_YOUNG_CHILD_13 i.partnered_imp13 TOTAL_INCOME_T_FAMILY13)) num_children_imp_hh13
(pmm, knn(5) include (num_children_imp_hh0 num_children_imp_hh1 num_children_imp_hh2 num_children_imp_hh3 num_children_imp_hh4 num_children_imp_hh5 num_children_imp_hh6 num_children_imp_hh7 num_children_imp_hh8 num_children_imp_hh9 num_children_imp_hh10 num_children_imp_hh11 num_children_imp_hh12 num_children_imp_hh13               weekly_hrs_t_focal14 housework_focal14 earnings_t_focal14 AGE_YOUNG_CHILD_14 i.partnered_imp14 TOTAL_INCOME_T_FAMILY14)) num_children_imp_hh14

/* Age of Youngest Child */
(pmm, knn(5) include (              AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14 weekly_hrs_t_focal0 housework_focal0 earnings_t_focal0 num_children_imp_hh0 i.partnered_imp0 TOTAL_INCOME_T_FAMILY0)) AGE_YOUNG_CHILD_0
(pmm, knn(5) include (             AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14  weekly_hrs_t_focal1 housework_focal1 earnings_t_focal1 num_children_imp_hh1 i.partnered_imp1 TOTAL_INCOME_T_FAMILY1)) AGE_YOUNG_CHILD_1
(pmm, knn(5) include (            AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14   weekly_hrs_t_focal2 housework_focal2 earnings_t_focal2 num_children_imp_hh2 i.partnered_imp2 TOTAL_INCOME_T_FAMILY2)) AGE_YOUNG_CHILD_2
(pmm, knn(5) include (           AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14    weekly_hrs_t_focal3 housework_focal3 earnings_t_focal3 num_children_imp_hh3 i.partnered_imp3 TOTAL_INCOME_T_FAMILY3)) AGE_YOUNG_CHILD_3
(pmm, knn(5) include (          AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14     weekly_hrs_t_focal4 housework_focal4 earnings_t_focal4 num_children_imp_hh4 i.partnered_imp4 TOTAL_INCOME_T_FAMILY4)) AGE_YOUNG_CHILD_4
(pmm, knn(5) include (         AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14      weekly_hrs_t_focal5 housework_focal5 earnings_t_focal5 num_children_imp_hh5 i.partnered_imp5 TOTAL_INCOME_T_FAMILY5)) AGE_YOUNG_CHILD_5
(pmm, knn(5) include (        AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14       weekly_hrs_t_focal6 housework_focal6 earnings_t_focal6 num_children_imp_hh6 i.partnered_imp6 TOTAL_INCOME_T_FAMILY6)) AGE_YOUNG_CHILD_6
(pmm, knn(5) include (       AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14        weekly_hrs_t_focal7 housework_focal7 earnings_t_focal7 num_children_imp_hh7 i.partnered_imp7 TOTAL_INCOME_T_FAMILY7)) AGE_YOUNG_CHILD_7
(pmm, knn(5) include (      AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14         weekly_hrs_t_focal8 housework_focal8 earnings_t_focal8 num_children_imp_hh8 i.partnered_imp8 TOTAL_INCOME_T_FAMILY8)) AGE_YOUNG_CHILD_8
(pmm, knn(5) include (     AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14          weekly_hrs_t_focal9 housework_focal9 earnings_t_focal9 num_children_imp_hh9 i.partnered_imp9 TOTAL_INCOME_T_FAMILY9)) AGE_YOUNG_CHILD_9
(pmm, knn(5) include (    AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14           weekly_hrs_t_focal10 housework_focal10 earnings_t_focal10 num_children_imp_hh10 i.partnered_imp10 TOTAL_INCOME_T_FAMILY10)) AGE_YOUNG_CHILD_10
(pmm, knn(5) include (   AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14            weekly_hrs_t_focal11 housework_focal11 earnings_t_focal11 num_children_imp_hh11 i.partnered_imp11 TOTAL_INCOME_T_FAMILY11)) AGE_YOUNG_CHILD_11
(pmm, knn(5) include (  AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_13 AGE_YOUNG_CHILD_14             weekly_hrs_t_focal12 housework_focal12 earnings_t_focal12 num_children_imp_hh12 i.partnered_imp12 TOTAL_INCOME_T_FAMILY12)) AGE_YOUNG_CHILD_12
(pmm, knn(5) include ( AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_14              weekly_hrs_t_focal13 housework_focal13 earnings_t_focal13 num_children_imp_hh13 i.partnered_imp13 TOTAL_INCOME_T_FAMILY13)) AGE_YOUNG_CHILD_13
(pmm, knn(5) include (AGE_YOUNG_CHILD_0 AGE_YOUNG_CHILD_1 AGE_YOUNG_CHILD_2 AGE_YOUNG_CHILD_3 AGE_YOUNG_CHILD_4 AGE_YOUNG_CHILD_5 AGE_YOUNG_CHILD_6 AGE_YOUNG_CHILD_7 AGE_YOUNG_CHILD_8 AGE_YOUNG_CHILD_9 AGE_YOUNG_CHILD_10 AGE_YOUNG_CHILD_11 AGE_YOUNG_CHILD_12 AGE_YOUNG_CHILD_13               weekly_hrs_t_focal14 housework_focal14 earnings_t_focal14 num_children_imp_hh14 i.partnered_imp14 TOTAL_INCOME_T_FAMILY14)) AGE_YOUNG_CHILD_14


/* Relationship to HH Head
(mlogit, include (                i.relationship_1 i.relationship_2 i.relationship_3 i.relationship_4 i.relationship_5 i.relationship_6 i.relationship_7 i.relationship_8 i.relationship_9 i.relationship_10 i.relationship_11 i.relationship_12 i.relationship_13 i.relationship_14 i.relationship_15 i.relationship_16)) relationship_0
(mlogit, include (               i.relationship_0 i.relationship_2 i.relationship_3 i.relationship_4 i.relationship_5 i.relationship_6 i.relationship_7 i.relationship_8 i.relationship_9 i.relationship_10 i.relationship_11 i.relationship_12 i.relationship_13 i.relationship_14 i.relationship_15 i.relationship_16 )) relationship_1
(mlogit, include (              i.relationship_0 i.relationship_1 i.relationship_3 i.relationship_4 i.relationship_5 i.relationship_6 i.relationship_7 i.relationship_8 i.relationship_9 i.relationship_10 i.relationship_11 i.relationship_12 i.relationship_13 i.relationship_14 i.relationship_15 i.relationship_16  )) relationship_2
(mlogit, include (             i.relationship_0 i.relationship_1 i.relationship_2 i.relationship_4 i.relationship_5 i.relationship_6 i.relationship_7 i.relationship_8 i.relationship_9 i.relationship_10 i.relationship_11 i.relationship_12 i.relationship_13 i.relationship_14 i.relationship_15 i.relationship_16   )) relationship_3
(mlogit, include (            i.relationship_0 i.relationship_1 i.relationship_2 i.relationship_3 i.relationship_5 i.relationship_6 i.relationship_7 i.relationship_8 i.relationship_9 i.relationship_10 i.relationship_11 i.relationship_12 i.relationship_13 i.relationship_14 i.relationship_15 i.relationship_16    )) relationship_4
(mlogit, include (           i.relationship_0 i.relationship_1 i.relationship_2 i.relationship_3 i.relationship_4 i.relationship_6 i.relationship_7 i.relationship_8 i.relationship_9 i.relationship_10 i.relationship_11 i.relationship_12 i.relationship_13 i.relationship_14 i.relationship_15 i.relationship_16     )) relationship_5
(mlogit, include (          i.relationship_0 i.relationship_1 i.relationship_2 i.relationship_3 i.relationship_4 i.relationship_5 i.relationship_7 i.relationship_8 i.relationship_9 i.relationship_10 i.relationship_11 i.relationship_12 i.relationship_13 i.relationship_14 i.relationship_15 i.relationship_16      )) relationship_6
(mlogit, include (         i.relationship_0 i.relationship_1 i.relationship_2 i.relationship_3 i.relationship_4 i.relationship_5 i.relationship_6 i.relationship_8 i.relationship_9 i.relationship_10 i.relationship_11 i.relationship_12 i.relationship_13 i.relationship_14 i.relationship_15 i.relationship_16       )) relationship_7
(mlogit, include (        i.relationship_0 i.relationship_1 i.relationship_2 i.relationship_3 i.relationship_4 i.relationship_5 i.relationship_6 i.relationship_7 i.relationship_9 i.relationship_10 i.relationship_11 i.relationship_12 i.relationship_13 i.relationship_14 i.relationship_15 i.relationship_16        )) relationship_8
(mlogit, include (       i.relationship_0 i.relationship_1 i.relationship_2 i.relationship_3 i.relationship_4 i.relationship_5 i.relationship_6 i.relationship_7 i.relationship_8 i.relationship_10 i.relationship_11 i.relationship_12 i.relationship_13 i.relationship_14 i.relationship_15 i.relationship_16         )) relationship_9
(mlogit, include (      i.relationship_0 i.relationship_1 i.relationship_2 i.relationship_3 i.relationship_4 i.relationship_5 i.relationship_6 i.relationship_7 i.relationship_8 i.relationship_9 i.relationship_11 i.relationship_12 i.relationship_13 i.relationship_14 i.relationship_15 i.relationship_16          )) relationship_10
(mlogit, include (     i.relationship_0 i.relationship_1 i.relationship_2 i.relationship_3 i.relationship_4 i.relationship_5 i.relationship_6 i.relationship_7 i.relationship_8 i.relationship_9 i.relationship_10 i.relationship_12 i.relationship_13 i.relationship_14 i.relationship_15 i.relationship_16           )) relationship_11
(mlogit, include (    i.relationship_0 i.relationship_1 i.relationship_2 i.relationship_3 i.relationship_4 i.relationship_5 i.relationship_6 i.relationship_7 i.relationship_8 i.relationship_9 i.relationship_10 i.relationship_11 i.relationship_13 i.relationship_14 i.relationship_15 i.relationship_16            )) relationship_12
(mlogit, include (   i.relationship_0 i.relationship_1 i.relationship_2 i.relationship_3 i.relationship_4 i.relationship_5 i.relationship_6 i.relationship_7 i.relationship_8 i.relationship_9 i.relationship_10 i.relationship_11 i.relationship_12 i.relationship_14 i.relationship_15 i.relationship_16             )) relationship_13
(mlogit, include (  i.relationship_0 i.relationship_1 i.relationship_2 i.relationship_3 i.relationship_4 i.relationship_5 i.relationship_6 i.relationship_7 i.relationship_8 i.relationship_9 i.relationship_10 i.relationship_11 i.relationship_12 i.relationship_13 i.relationship_15 i.relationship_16              )) relationship_14
(mlogit, include ( i.relationship_0 i.relationship_1 i.relationship_2 i.relationship_3 i.relationship_4 i.relationship_5 i.relationship_6 i.relationship_7 i.relationship_8 i.relationship_9 i.relationship_10 i.relationship_11 i.relationship_12 i.relationship_13 i.relationship_14 i.relationship_16               )) relationship_15
(mlogit, include (i.relationship_0 i.relationship_1 i.relationship_2 i.relationship_3 i.relationship_4 i.relationship_5 i.relationship_6 i.relationship_7 i.relationship_8 i.relationship_9 i.relationship_10 i.relationship_11 i.relationship_12 i.relationship_13 i.relationship_14 i.relationship_15                )) relationship_16
*/

/* Partnership Status */
(logit, include (              i.partnered_imp1 i.partnered_imp2 i.partnered_imp3 i.partnered_imp4 i.partnered_imp5 i.partnered_imp6 i.partnered_imp7 i.partnered_imp8 i.partnered_imp9 i.partnered_imp10 i.partnered_imp11 i.partnered_imp12 i.partnered_imp13 i.partnered_imp14 weekly_hrs_t_focal0 housework_focal0 num_children_imp_hh0 AGE_YOUNG_CHILD_0 earnings_t_focal0 TOTAL_INCOME_T_FAMILY0)) partnered_imp0
(logit, include (             i.partnered_imp0 i.partnered_imp2 i.partnered_imp3 i.partnered_imp4 i.partnered_imp5 i.partnered_imp6 i.partnered_imp7 i.partnered_imp8 i.partnered_imp9 i.partnered_imp10 i.partnered_imp11 i.partnered_imp12 i.partnered_imp13 i.partnered_imp14  weekly_hrs_t_focal1 housework_focal1 num_children_imp_hh1 AGE_YOUNG_CHILD_1 earnings_t_focal1 TOTAL_INCOME_T_FAMILY1)) partnered_imp1
(logit, include (            i.partnered_imp0 i.partnered_imp1 i.partnered_imp3 i.partnered_imp4 i.partnered_imp5 i.partnered_imp6 i.partnered_imp7 i.partnered_imp8 i.partnered_imp9 i.partnered_imp10 i.partnered_imp11 i.partnered_imp12 i.partnered_imp13 i.partnered_imp14   weekly_hrs_t_focal2 housework_focal2 num_children_imp_hh2 AGE_YOUNG_CHILD_2 earnings_t_focal2 TOTAL_INCOME_T_FAMILY2)) partnered_imp2
(logit, include (           i.partnered_imp0 i.partnered_imp1 i.partnered_imp2 i.partnered_imp4 i.partnered_imp5 i.partnered_imp6 i.partnered_imp7 i.partnered_imp8 i.partnered_imp9 i.partnered_imp10 i.partnered_imp11 i.partnered_imp12 i.partnered_imp13 i.partnered_imp14    weekly_hrs_t_focal3 housework_focal3 num_children_imp_hh3 AGE_YOUNG_CHILD_3 earnings_t_focal3 TOTAL_INCOME_T_FAMILY3)) partnered_imp3
(logit, include (          i.partnered_imp0 i.partnered_imp1 i.partnered_imp2 i.partnered_imp3 i.partnered_imp5 i.partnered_imp6 i.partnered_imp7 i.partnered_imp8 i.partnered_imp9 i.partnered_imp10 i.partnered_imp11 i.partnered_imp12 i.partnered_imp13 i.partnered_imp14     weekly_hrs_t_focal4 housework_focal4 num_children_imp_hh4 AGE_YOUNG_CHILD_4 earnings_t_focal4 TOTAL_INCOME_T_FAMILY4)) partnered_imp4
(logit, include (         i.partnered_imp0 i.partnered_imp1 i.partnered_imp2 i.partnered_imp3 i.partnered_imp4 i.partnered_imp6 i.partnered_imp7 i.partnered_imp8 i.partnered_imp9 i.partnered_imp10 i.partnered_imp11 i.partnered_imp12 i.partnered_imp13 i.partnered_imp14      weekly_hrs_t_focal5 housework_focal5 num_children_imp_hh5 AGE_YOUNG_CHILD_5 earnings_t_focal5 TOTAL_INCOME_T_FAMILY5)) partnered_imp5
(logit, include (        i.partnered_imp0 i.partnered_imp1 i.partnered_imp2 i.partnered_imp3 i.partnered_imp4 i.partnered_imp5 i.partnered_imp7 i.partnered_imp8 i.partnered_imp9 i.partnered_imp10 i.partnered_imp11 i.partnered_imp12 i.partnered_imp13 i.partnered_imp14       weekly_hrs_t_focal6 housework_focal6 num_children_imp_hh6 AGE_YOUNG_CHILD_6 earnings_t_focal6 TOTAL_INCOME_T_FAMILY6)) partnered_imp6
(logit, include (       i.partnered_imp0 i.partnered_imp1 i.partnered_imp2 i.partnered_imp3 i.partnered_imp4 i.partnered_imp5 i.partnered_imp6 i.partnered_imp8 i.partnered_imp9 i.partnered_imp10 i.partnered_imp11 i.partnered_imp12 i.partnered_imp13 i.partnered_imp14        weekly_hrs_t_focal7 housework_focal7 num_children_imp_hh7 AGE_YOUNG_CHILD_7 earnings_t_focal7 TOTAL_INCOME_T_FAMILY7)) partnered_imp7
(logit, include (      i.partnered_imp0 i.partnered_imp1 i.partnered_imp2 i.partnered_imp3 i.partnered_imp4 i.partnered_imp5 i.partnered_imp6 i.partnered_imp7 i.partnered_imp9 i.partnered_imp10 i.partnered_imp11 i.partnered_imp12 i.partnered_imp13 i.partnered_imp14         weekly_hrs_t_focal8 housework_focal8 num_children_imp_hh8 AGE_YOUNG_CHILD_8 earnings_t_focal8 TOTAL_INCOME_T_FAMILY8)) partnered_imp8
(logit, include (     i.partnered_imp0 i.partnered_imp1 i.partnered_imp2 i.partnered_imp3 i.partnered_imp4 i.partnered_imp5 i.partnered_imp6 i.partnered_imp7 i.partnered_imp8 i.partnered_imp10 i.partnered_imp11 i.partnered_imp12 i.partnered_imp13 i.partnered_imp14          weekly_hrs_t_focal9 housework_focal9 num_children_imp_hh9 AGE_YOUNG_CHILD_9 earnings_t_focal9 TOTAL_INCOME_T_FAMILY9)) partnered_imp9
(logit, include (    i.partnered_imp0 i.partnered_imp1 i.partnered_imp2 i.partnered_imp3 i.partnered_imp4 i.partnered_imp5 i.partnered_imp6 i.partnered_imp7 i.partnered_imp8 i.partnered_imp9 i.partnered_imp11 i.partnered_imp12 i.partnered_imp13 i.partnered_imp14           weekly_hrs_t_focal10 housework_focal10 num_children_imp_hh10 AGE_YOUNG_CHILD_10 earnings_t_focal10 TOTAL_INCOME_T_FAMILY10)) partnered_imp10
(logit, include (   i.partnered_imp0 i.partnered_imp1 i.partnered_imp2 i.partnered_imp3 i.partnered_imp4 i.partnered_imp5 i.partnered_imp6 i.partnered_imp7 i.partnered_imp8 i.partnered_imp9 i.partnered_imp10 i.partnered_imp12 i.partnered_imp13 i.partnered_imp14            weekly_hrs_t_focal11 housework_focal11 num_children_imp_hh11 AGE_YOUNG_CHILD_11 earnings_t_focal11 TOTAL_INCOME_T_FAMILY11)) partnered_imp11
(logit, include (  i.partnered_imp0 i.partnered_imp1 i.partnered_imp2 i.partnered_imp3 i.partnered_imp4 i.partnered_imp5 i.partnered_imp6 i.partnered_imp7 i.partnered_imp8 i.partnered_imp9 i.partnered_imp10 i.partnered_imp11 i.partnered_imp13 i.partnered_imp14             weekly_hrs_t_focal12 housework_focal12 num_children_imp_hh12 AGE_YOUNG_CHILD_12 earnings_t_focal12 TOTAL_INCOME_T_FAMILY12)) partnered_imp12
(logit, include ( i.partnered_imp0 i.partnered_imp1 i.partnered_imp2 i.partnered_imp3 i.partnered_imp4 i.partnered_imp5 i.partnered_imp6 i.partnered_imp7 i.partnered_imp8 i.partnered_imp9 i.partnered_imp10 i.partnered_imp11 i.partnered_imp12 i.partnered_imp14              weekly_hrs_t_focal13 housework_focal13 num_children_imp_hh13 AGE_YOUNG_CHILD_13 earnings_t_focal13 TOTAL_INCOME_T_FAMILY13)) partnered_imp13
(logit, include (i.partnered_imp0 i.partnered_imp1 i.partnered_imp2 i.partnered_imp3 i.partnered_imp4 i.partnered_imp5 i.partnered_imp6 i.partnered_imp7 i.partnered_imp8 i.partnered_imp9 i.partnered_imp10 i.partnered_imp11 i.partnered_imp12 i.partnered_imp13               weekly_hrs_t_focal14 housework_focal14 num_children_imp_hh14 AGE_YOUNG_CHILD_14 earnings_t_focal14 TOTAL_INCOME_T_FAMILY14)) partnered_imp14

/* Family Income */
(pmm, knn(5) include (              TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 weekly_hrs_t_focal0 housework_focal0 earnings_t_focal0 num_children_imp_hh0 i.partnered_imp0 AGE_YOUNG_CHILD_0)) TOTAL_INCOME_T_FAMILY0
(pmm, knn(5) include (             TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14  weekly_hrs_t_focal1 housework_focal1 earnings_t_focal1 num_children_imp_hh1 i.partnered_imp1 AGE_YOUNG_CHILD_1)) TOTAL_INCOME_T_FAMILY1
(pmm, knn(5) include (            TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14   weekly_hrs_t_focal2 housework_focal2 earnings_t_focal2 num_children_imp_hh2 i.partnered_imp2 AGE_YOUNG_CHILD_2)) TOTAL_INCOME_T_FAMILY2
(pmm, knn(5) include (           TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14    weekly_hrs_t_focal3 housework_focal3 earnings_t_focal3 num_children_imp_hh3 i.partnered_imp3 AGE_YOUNG_CHILD_3)) TOTAL_INCOME_T_FAMILY3
(pmm, knn(5) include (          TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14     weekly_hrs_t_focal4 housework_focal4 earnings_t_focal4 num_children_imp_hh4 i.partnered_imp4 AGE_YOUNG_CHILD_4)) TOTAL_INCOME_T_FAMILY4
(pmm, knn(5) include (         TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14      weekly_hrs_t_focal5 housework_focal5 earnings_t_focal5 num_children_imp_hh5 i.partnered_imp5 AGE_YOUNG_CHILD_5)) TOTAL_INCOME_T_FAMILY5
(pmm, knn(5) include (        TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14       weekly_hrs_t_focal6 housework_focal6 earnings_t_focal6 num_children_imp_hh6 i.partnered_imp6 AGE_YOUNG_CHILD_6)) TOTAL_INCOME_T_FAMILY6
(pmm, knn(5) include (       TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14        weekly_hrs_t_focal7 housework_focal7 earnings_t_focal7 num_children_imp_hh7 i.partnered_imp7 AGE_YOUNG_CHILD_7)) TOTAL_INCOME_T_FAMILY7
(pmm, knn(5) include (      TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14         weekly_hrs_t_focal8 housework_focal8 earnings_t_focal8 num_children_imp_hh8 i.partnered_imp8 AGE_YOUNG_CHILD_8)) TOTAL_INCOME_T_FAMILY8
(pmm, knn(5) include (     TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14          weekly_hrs_t_focal9 housework_focal9 earnings_t_focal9 num_children_imp_hh9 i.partnered_imp9 AGE_YOUNG_CHILD_9)) TOTAL_INCOME_T_FAMILY9
(pmm, knn(5) include (    TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14           weekly_hrs_t_focal10 housework_focal10 earnings_t_focal10 num_children_imp_hh10 i.partnered_imp10 AGE_YOUNG_CHILD_10)) TOTAL_INCOME_T_FAMILY10
(pmm, knn(5) include (   TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14            weekly_hrs_t_focal11 housework_focal11 earnings_t_focal11 num_children_imp_hh11 i.partnered_imp11 AGE_YOUNG_CHILD_11)) TOTAL_INCOME_T_FAMILY11
(pmm, knn(5) include (  TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14             weekly_hrs_t_focal12 housework_focal12 earnings_t_focal12 num_children_imp_hh12 i.partnered_imp12 AGE_YOUNG_CHILD_12)) TOTAL_INCOME_T_FAMILY12
(pmm, knn(5) include ( TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY14              weekly_hrs_t_focal13 housework_focal13 earnings_t_focal13 num_children_imp_hh13 i.partnered_imp13 AGE_YOUNG_CHILD_13)) TOTAL_INCOME_T_FAMILY13
(pmm, knn(5) include (TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13               weekly_hrs_t_focal14 housework_focal14 earnings_t_focal14 num_children_imp_hh14 i.partnered_imp14 AGE_YOUNG_CHILD_14)) TOTAL_INCOME_T_FAMILY14

= birth_yr_all i.raceth_fixed_focal i.sample_type i.fixed_education, by(SEX) chaindots add(10) rseed(12345) noimputed augment force showcommand  // dryrun // noisily i.rel_start_all  FIRST_BIRTH_YR i.rel_type_constant 

;
#delimit cr

// log close

// = i.FIRST_BIRTH_YR i.birth_yr_all i.rel_start_all i.raceth_fixed_focal i.sample_type i.SEX, chaindots add(1) rseed(12345) noimputed augment noisily force // dryrun

// save "$created_data/psid_individs_imputed_wide_bysex", replace // okay, now that this worked with more variables, will replace above version
